### ISSUE TITLE
ProtocolLib unable to clone chat packets

### ISSUE THREAD

**Issue by MisterLolxd2** [LOOHP/InteractiveChat#104]
Hello, I use something like "auto messages" in the script plugin (Skript 2.6.2, fork 1.8), and generally messages that are simply blocked (with many errors) by interactivechat after a long time from the server start.
Sorry for my English.

Inteactive chat: 4.2.2.0
Java: 8
Server ver: Flame Paper 1.8.8
Dependencies
  Protocollib: 4.8.0
  Placeholderapi. 2.11.2
  Vault: 1.7.3
Errors: https://pastebin.com/1aq0xQj0

**Comment by LOOHP** [comment]
I suggest you to report this to ProtocolLib

**Comment by MisterLolxd2** [comment]
The problem disappears after switching off interactivechat.
So I don't understand why ProtocolLib is in the unstable version 5.0.0 for now.

**Comment by LOOHP** [comment]
InteractiveChat calls ProtocolLib methods. Disabling InteractiveChat makes the error go away doesn't automatically means that only InteractiveChat is at fault. I believe this might be an issue with ProtocolLib.

**Comment by LOOHP** [comment]
Well, you can always try it out and see. If it still happens on ProtocolLib 5.0.0-SNAPSHOT, then report this to ProtocolLib.

**Comment by MisterLolxd2** [comment]
Hmm, after the update:
CombatLog: R.I.P
Interactive Chat: I don't know, because combatlogx has errors, and the interactivechat error occurred only after some time (1h +). So I went back to protocollib 4.8.0 and got rid of interactivechat, well.

**Comment by MisterLolxd2** [comment]
Alternatively it will try to update the combatlogx which works with protocollib 5.0.0 and test if interactivechat will work properly. It will take me a while.

**Comment by MisterLolxd2** [comment]
https://pastebin.com/kR1LCVVY

Nope. Each script message is sent as 2 blank lines (canceled) via your plugin, not protocollib.

**Comment by LOOHP** [comment]
This error you send me looks weird, there aren't any stacktraces. Do you mind sending your complete logs?

**Comment by MisterLolxd2** [comment]
[18:22:56] [Server thread/ERROR]: [InteractiveChat] Unhandled exception occured in onPacketSending(PacketEvent) for InteractiveChat
java.lang.RuntimeException: Unable to clone object PacketContainer[type=CHAT[class=PacketPlayOutChat, id=15], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[private net.minecraft.server.v1_8_R3.IChatBaseComponent net.minecraft.server.v1_8_R3.PacketPlayOutChat.a, public net.md_5.bungee.api.chat.BaseComponent[] net.minecraft.server.v1_8_R3.PacketPlayOutChat.components, private byte net.minecraft.server.v1_8_R3.PacketPlayOutChat.b]]] (com.comphenix.protocol.events.PacketContainer)
	at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:44) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:256) ~[?:?]
	at com.loohp.interactivechat.listeners.OutMessagePacket$1.onPacketSending(OutMessagePacket.java:375) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:911) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.EntityPlayer.sendMessage(EntityPlayer.java:980) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.CommandDispatcher.a(CommandDispatcher.java:97) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.CommandAbstract.a(SourceFile:522) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.CommandAbstract.a(SourceFile:517) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.CommandKick.execute(SourceFile:52) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.craftbukkit.v1_8_R3.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:123) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.craftbukkit.v1_8_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:44) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:596) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at me.frep.vulcan.spigot.Vulcan_u3.Vulcan_L(Vulcan_u3.java:98) ~[?:?]
	at me.frep.vulcan.spigot.Vulcan_hG.lambda$run$0(Vulcan_hG.java:219) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_312]
	at me.frep.vulcan.spigot.Vulcan_hG.run(Vulcan_hG.java:191) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:750) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:366) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:680) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:583) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: java.io.IOException: Could not deserialize Minecraft packet.
	at com.comphenix.protocol.events.PacketContainer.readObject(PacketContainer.java:353) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2296) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461) ~[?:1.8.0_312]
	at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:42) ~[?:?]
	... 38 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at com.comphenix.protocol.events.PacketContainer.readObject(PacketContainer.java:347) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2296) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461) ~[?:1.8.0_312]
	at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:42) ~[?:?]
	... 38 more
Caused by: com.google.gson.JsonParseException: Stacked with ChatComponent elements
	at net.minecraft.server.v1_8_R3.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:102) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:115) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:184) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:286) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:1) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at com.google.gson.Gson.fromJson(Gson.java:689) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:276) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.PacketDataSerializer.d(PacketDataSerializer.java:73) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.PacketPlayOutChat.a(PacketPlayOutChat.java:23) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at com.comphenix.protocol.events.PacketContainer.readObject(PacketContainer.java:347) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2296) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461) ~[?:1.8.0_312]
	at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:42) ~[?:?]
	... 38 more
[18:22:56] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayOutChat@38fa8068[
    a=TranslatableComponent{key='chat.type.admin', args=[Server, TranslatableComponent{key='commands.kick.success.reason', args=[Mart0lini, Internal Exception: io.netty.handler.timeout.ReadTimeoutException], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=§7, bold=null, italic=true, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
    components=<null>
    b=1
  ]

[18:22:56] [Server thread/INFO]: Kicked Mart0lini from the game: 'Internal Exception: io.netty.handler.timeout.ReadTimeoutException'
[18:22:56] [Server thread/WARN]: handleDisconnection() called twice
[18:23:03] [Server thread/INFO]: Mateuszkrol lost connection: Disconnected
[18:23:08] [Thread-663/INFO]: UUID of player Z0diaC01 is 7fcba609-ed8c-3dad-a9e8-ac67b49eaa73
[18:23:08] [pool-60-thread-53/INFO]: [SG-New VV] Player Z0diaC01 version: 47
[18:23:08] [pool-60-thread-53/INFO]: [SG-New VV] Player Z0diaC01 version: 47
[18:23:08] [Server thread/INFO]: Z0diaC01[/94.101.18.210:37537] logged in with entity id 91782 at ([pvpclassic]37.5, 61.0, 8.5)
[18:23:14] [Server thread/ERROR]: [InteractiveChat] Unhandled exception occured in onPacketSending(PacketEvent) for InteractiveChat
java.lang.RuntimeException: Unable to clone object PacketContainer[type=CHAT[class=PacketPlayOutChat, id=15], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[private net.minecraft.server.v1_8_R3.IChatBaseComponent net.minecraft.server.v1_8_R3.PacketPlayOutChat.a, public net.md_5.bungee.api.chat.BaseComponent[] net.minecraft.server.v1_8_R3.PacketPlayOutChat.components, private byte net.minecraft.server.v1_8_R3.PacketPlayOutChat.b]]] (com.comphenix.protocol.events.PacketContainer)
	at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:44) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:256) ~[?:?]
	at com.loohp.interactivechat.listeners.OutMessagePacket$1.onPacketSending(OutMessagePacket.java:375) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:911) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer$1.sendMessage(CraftPlayer.java:1569) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:153) ~[?:?]
	at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:127) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:51) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
	at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142) ~[?:?]
	at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53) ~[?:?]
	at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:721) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:741) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:366) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:680) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:583) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: java.io.IOException: Could not deserialize Minecraft packet.
	at com.comphenix.protocol.events.PacketContainer.readObject(PacketContainer.java:353) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor923.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2296) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461) ~[?:1.8.0_312]
	at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:42) ~[?:?]
	... 46 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor922.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at com.comphenix.protocol.events.PacketContainer.readObject(PacketContainer.java:347) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor923.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2296) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461) ~[?:1.8.0_312]
	at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:42) ~[?:?]
	... 46 more
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(1765) exceeds writerIndex(1019): UnpooledUnsafeDirectByteBuf(ridx: 2, widx: 1019, cap: 2048)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:655) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.PacketDataSerializer.readBytes(PacketDataSerializer.java:571) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.PacketDataSerializer.c(PacketDataSerializer.java:224) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.PacketDataSerializer.d(PacketDataSerializer.java:73) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.PacketPlayOutChat.a(PacketPlayOutChat.java:23) ~[FlamePaper.jar:git-PaperSpigot-"f6b10d47"]
	at sun.reflect.GeneratedMethodAccessor922.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at com.comphenix.protocol.events.PacketContainer.readObject(PacketContainer.java:347) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor923.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2296) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461) ~[?:1.8.0_312]
	at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:42) ~[?:?]
	... 46 more
[18:23:14] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayOutChat@1eb522b5[
    a=<null>
    components={TextComponent{text=, BaseComponent(color=§f, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=, BaseComponent(color=§8, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=[, BaseComponent(color=§8, bold=true, italic=false, underlined=false, strikethrough=false, obfuscated=false, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=, BaseComponent(color=§6, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=PVP, BaseComponent(color=§6, bold=true, italic=false, underlined=false, strikethrough=false, obfuscated=false, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=, BaseComponent(color=§e, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=CLASSIC, BaseComponent(color=§e, bold=true, italic=false, underlined=false, strikethrough=false, obfuscated=false, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=, BaseComponent(color=§8, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=], BaseComponent(color=§8, bold=true, italic=false, underlined=false, strikethrough=false, obfuscated=false, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=, BaseComponent(color=§f, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text= , BaseComponent(color=§f, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=Otrzymałeś , BaseComponent(color=§a, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=, BaseComponent(color=§4, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=+10 , BaseComponent(color=§4, bold=true, italic=false, underlined=false, strikethrough=false, obfuscated=false, insertion=null, extra=null, clickEvent=null, hoverEvent=null)},TextComponent{text=serc!, BaseComponent(color=§a, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}}
    b=0
  ]

**Comment by LOOHP** [comment]
It's the same problem as the one you posted originally. You should report that to ProtocolLib.
