### ISSUE TITLE
Unable to load on Bungee 1.19

### ISSUE THREAD

**Issue by twseer67875** [LOOHP/InteractiveChat#106]
This problem is suspected to be caused by changes in PlayerChat after the 1.19.1 update

```
Bungeecord Version: Waterfall version git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5b246ea:499
Plugin Version: 4.2.2.0
```

Error Message
```
[15:08:07] [main/WARN]: Error loading plugin InteractiveChatBungee
java.lang.NoClassDefFoundError: net/md_5/bungee/protocol/packet/PlayerChat
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:395) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5b246ea:499]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5b246ea:499]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5b246ea:499]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5b246ea:499]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5b246ea:499]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.protocol.packet.PlayerChat
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5b246ea:499]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5b246ea:499]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 9 more
```

**Comment by LOOHP** [comment]
1.19.1 support will come eventually, thank you for being patient.
