### ISSUE TITLE
1.19.1 BUG - FieldAccessException: Field index 0 is out of bounds for length 0

### ISSUE THREAD

**Issue by Futodama** [LOOHP/InteractiveChat#108]
[17:23:55 WARN]: FieldAccessException: Field index 0 is out of bounds for length 0
[17:23:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49)
[17:23:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:218)
[17:23:55 WARN]:        at InteractiveChat-4.2.2.6.jar//com.loohp.interactivechat.listeners.OutMessagePacket.lambda$static$9(OutMessagePacket.java:217)
[17:23:55 WARN]:        at InteractiveChat-4.2.2.6.jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.onPacketSending(OutMessagePacket.java:363)
[17:23:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[17:23:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[17:23:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
[17:23:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[17:23:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:94)
[17:23:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:527)
[17:23:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:469)
[17:23:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220)
[17:23:55 WARN]:        at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:432)
[17:23:55 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:379)
[17:23:55 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2165)
[17:23:55 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2151)
[17:23:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23)
[17:23:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.sendServerPacket(NettyChannelInjector.java:289)
[17:23:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$processOutbound$2(NettyChannelInjector.java:521)
[17:23:55 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:23:55 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[17:23:55 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1491)
[17:23:55 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[17:23:55 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1415)
[17:23:55 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1191)
[17:23:55 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[17:23:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:23:56 WARN]: FieldAccessException: Field index 0 is out of bounds for length 0
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:218)
[17:23:56 WARN]:        at InteractiveChat-4.2.2.6.jar//com.loohp.interactivechat.listeners.OutMessagePacket.lambda$static$9(OutMessagePacket.java:217)
[17:23:56 WARN]:        at InteractiveChat-4.2.2.6.jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.onPacketSending(OutMessagePacket.java:363)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:94)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:527)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:469)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220)
[17:23:56 WARN]:        at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:432)
[17:23:56 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:379)
[17:23:56 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2165)
[17:23:56 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2151)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.sendServerPacket(NettyChannelInjector.java:289)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$processOutbound$2(NettyChannelInjector.java:521)
[17:23:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:23:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[17:23:56 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1491)
[17:23:56 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[17:23:56 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1415)
[17:23:56 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1191)
[17:23:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[17:23:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:23:56 WARN]: FieldAccessException: Field index 0 is out of bounds for length 0
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:218)
[17:23:56 WARN]:        at InteractiveChat-4.2.2.6.jar//com.loohp.interactivechat.listeners.OutMessagePacket.lambda$static$9(OutMessagePacket.java:217)
[17:23:56 WARN]:        at InteractiveChat-4.2.2.6.jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.onPacketSending(OutMessagePacket.java:363)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:94)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:527)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:469)
[17:23:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220)
[17:23:56 WARN]:        at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:432)
[17:23:56 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:379)
[17:23:56 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2165)
[17:23:56 WARN]:        at net.minecraft.server.level.EntityPlayer.b(EntityPlayer.java:1873)
[17:23:56 WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1868)
[17:23:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:248)
[17:23:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:264)
[17:23:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:271)
[17:23:56 WARN]:        at AuthMe-5.6.0-SNAPSHOT.jar//fr.xephi.authme.task.MessageTask.run(MessageTask.java:31)
[17:23:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:23:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[17:23:56 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1491)
[17:23:56 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[17:23:56 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1415)
[17:23:56 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1191)
[17:23:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[17:23:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:24:05 WARN]: FieldAccessException: Field index 0 is out of bounds for length 0
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:218)
[17:24:05 WARN]:        at InteractiveChat-4.2.2.6.jar//com.loohp.interactivechat.listeners.OutMessagePacket.lambda$static$9(OutMessagePacket.java:217)
[17:24:05 WARN]:        at InteractiveChat-4.2.2.6.jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.onPacketSending(OutMessagePacket.java:363)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:94)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:527)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:469)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220)
[17:24:05 WARN]:        at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:432)
[17:24:05 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:379)
[17:24:05 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2165)
[17:24:05 WARN]:        at net.minecraft.server.level.EntityPlayer.b(EntityPlayer.java:1873)
[17:24:05 WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1868)
[17:24:05 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:248)
[17:24:05 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:264)
[17:24:05 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:271)
[17:24:05 WARN]:        at AuthMe-5.6.0-SNAPSHOT.jar//fr.xephi.authme.task.MessageTask.run(MessageTask.java:31)
[17:24:05 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:24:05 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[17:24:05 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1491)
[17:24:05 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[17:24:05 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1415)
[17:24:05 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1191)
[17:24:05 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[17:24:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:24:05 WARN]: FieldAccessException: Field index 0 is out of bounds for length 0
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:218)
[17:24:05 WARN]:        at InteractiveChat-4.2.2.6.jar//com.loohp.interactivechat.listeners.OutMessagePacket.lambda$static$9(OutMessagePacket.java:217)
[17:24:05 WARN]:        at InteractiveChat-4.2.2.6.jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.onPacketSending(OutMessagePacket.java:363)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:94)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:527)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:469)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220)
[17:24:05 WARN]:        at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:432)
[17:24:05 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:379)
[17:24:05 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2165)
[17:24:05 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2151)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.sendServerPacket(NettyChannelInjector.java:289)
[17:24:05 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$processOutbound$2(NettyChannelInjector.java:521)
[17:24:05 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:24:05 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[17:24:05 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1491)
[17:24:05 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[17:24:05 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1415)
[17:24:05 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1191)
[17:24:05 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[17:24:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:24:12 INFO]: Gekata issued server command: /bukkit:pl
[17:24:12 WARN]: FieldAccessException: Field index 0 is out of bounds for length 0
[17:24:12 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49)
[17:24:12 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:218)
[17:24:12 WARN]:        at InteractiveChat-4.2.2.6.jar//com.loohp.interactivechat.listeners.OutMessagePacket.lambda$static$9(OutMessagePacket.java:217)
[17:24:12 WARN]:        at InteractiveChat-4.2.2.6.jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.onPacketSending(OutMessagePacket.java:363)
[17:24:12 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[17:24:12 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[17:24:12 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
[17:24:12 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[17:24:12 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:94)
[17:24:12 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:527)
[17:24:12 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:469)
[17:24:12 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220)
[17:24:12 WARN]:        at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:432)
[17:24:12 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:379)
[17:24:12 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2165)
[17:24:12 WARN]:        at net.minecraft.server.level.EntityPlayer.b(EntityPlayer.java:1873)
[17:24:12 WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1868)
[17:24:12 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:248)
[17:24:12 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:264)
[17:24:12 WARN]:        at org.bukkit.command.defaults.PluginsCommand.execute(PluginsCommand.java:28)
[17:24:12 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[17:24:12 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[17:24:12 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:59)
[17:24:12 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[17:24:12 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:306)
[17:24:12 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:290)
[17:24:12 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2283)
[17:24:12 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
[17:24:12 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[17:24:12 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[17:24:12 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:24:12 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[17:24:12 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[17:24:12 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1359)
[17:24:12 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[17:24:12 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[17:24:12 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1336)
[17:24:12 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1329)
[17:24:12 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bq(IAsyncTaskHandler.java:114)
[17:24:12 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1463)
[17:24:12 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1191)
[17:24:12 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[17:24:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:24:15 WARN]: [Trails] Loaded class com.sk89q.worldedit.bukkit.BukkitAdapter from WorldEdit v7.2.11+c43a877 which is not a depend or softdepend of this plugin.

**Comment by LOOHP** [comment]
1.19.1 support will come eventually, thank you for being patient.
If you want to give insider dev builds a try, join my [discord server](http://dev.discord.loohpjames.com)
