### ISSUE TITLE
not loading on 1.19.3 ?

### ISSUE THREAD

**Issue by comonier** [LOOHP/InteractiveChat#132]
```yaml
[23:38:01] [Server thread/INFO]: [InteractiveChat] Enabling InteractiveChat v4.2.5.3
[23:38:02] [JDA MainWS-ReadThread/INFO]: [DiscordSRV] [JDA] Finished Loading!
[23:38:02] [Server thread/WARN]: com.loohp.interactivechat.libs.org.simpleyaml.exceptions.InvalidConfigurationException: while scanning for the next token
[23:38:02] [Server thread/WARN]: found character '@' that cannot start any token. (Do not use @ for indentation)
[23:38:02] [Server thread/WARN]:  in 'reader', line 165, column 18:
[23:38:02] [Server thread/WARN]:       MentionPrefix: @
[23:38:02] [Server thread/WARN]:                      ^
[23:38:02] [Server thread/WARN]: 
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.simpleyaml.configuration.implementation.SimpleYamlImplementation.load(SimpleYamlImplementation.java:78)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.simpleyaml.configuration.implementation.SimpleYamlImplementation.load(SimpleYamlImplementation.java:57)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.simpleyaml.configuration.file.YamlConfiguration.load(YamlConfiguration.java:134)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.simpleyaml.configuration.file.YamlFile.load(YamlFile.java:579)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.simpleyaml.configuration.file.YamlConfiguration.load(YamlConfiguration.java:272)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.simpleyaml.configuration.file.YamlConfiguration.load(YamlConfiguration.java:199)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.config.Config.<init>(Config.java:122)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.config.Config.loadConfig(Config.java:68)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.config.ConfigManager.setup(ConfigManager.java:64)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.InteractiveChat.onEnable(InteractiveChat.java:424)
[23:38:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[23:38:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
[23:38:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544)
[23:38:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578)
[23:38:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492)
[23:38:02] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[23:38:02] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[23:38:02] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:301)
[23:38:02] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[23:38:02] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[23:38:02] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:38:02] [Server thread/WARN]: Caused by: while scanning for the next token
[23:38:02] [Server thread/WARN]: found character '@' that cannot start any token. (Do not use @ for indentation)
[23:38:02] [Server thread/WARN]:  in 'reader', line 165, column 18:
[23:38:02] [Server thread/WARN]:       MentionPrefix: @
[23:38:02] [Server thread/WARN]:                      ^
[23:38:02] [Server thread/WARN]: 
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:460)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:251)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:660)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.composer.Composer.composeKeyNode(Composer.java:310)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:301)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.yaml.snakeyaml.Yaml.load(Yaml.java:442)
[23:38:02] [Server thread/WARN]: 	at InteractiveChat-4.2.5.3.jar//com.loohp.interactivechat.libs.org.simpleyaml.configuration.implementation.SimpleYamlImplementation.load(SimpleYamlImplementation.java:72)
[23:38:02] [Server thread/WARN]: 	... 20 more
[23:38:02] [Server thread/INFO]: [InteractiveChat] Disabling InteractiveChat v4.2.5.3
[23:38:02] [Server thread/ERROR]: Error occurred while disabling InteractiveChat v4.2.5.3 (Is it up to date?)
java.lang.NoSuchFieldError: DISGUISED_CHAT
	at com.loohp.interactivechat.listeners.OutMessagePacket.<clinit>(OutMessagePacket.java:93) ~[InteractiveChat-4.2.5.3.jar:?]
	at com.loohp.interactivechat.InteractiveChat.onDisable(InteractiveChat.java:665) ~[InteractiveChat-4.2.5.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:400) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:581) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at com.loohp.interactivechat.InteractiveChat.onEnable(InteractiveChat.java:427) ~[InteractiveChat-4.2.5.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-364]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:301) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-364]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-364]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	```

**Comment by LOOHP** [comment]
Change @ to "@" in the config
