### ISSUE TITLE
Cause SecureException when using with CodeChickenLib and ForgeMultipart

### ISSUE THREAD

**Issue by MrMks** [LOOHP/InteractiveChat#137]
Running on newest [CatServer](https://github.com/Luohuayu/CatServer/tree/1.12.2) for 1.12.2, and if I remove this plugin, such exception will disapear.

```log
java.lang.NoClassDefFoundError: codechicken/multipart/TickScheduler$ChunkTickScheduler$$anonfun$saveData$1
	at codechicken.multipart.TickScheduler$ChunkTickScheduler.saveData(TickScheduler.scala:184)
	at codechicken.lib.world.WorldExtension.saveChunkData(WorldExtension.java:63)
	at codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkDataSave(WorldExtensionManager.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_WorldExtensionEventHandler_onChunkDataSave_Save.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:176)
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:212)
	at net.minecraft.world.gen.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:337)
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:288)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:308)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:971)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: codechicken.multipart.TickScheduler$ChunkTickScheduler$$anonfun$saveData$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 16 more
Caused by: java.lang.SecurityException: class "codechicken.multipart.TickScheduler$ChunkTickScheduler$$anonfun$saveData$1"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:891)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:661)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:754)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 18 more
```

**Comment by LOOHP** [comment]
I think you should report this to CatServer. This error does not occur on actual Spigot forks.

**Comment by LOOHP** [comment]
Inactive
