### ISSUE TITLE
Issue when a player disconnect

### ISSUE THREAD

**Issue by Xitryne** [LOOHP/InteractiveChat#146]
WARN01:58:55
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.get(Object)" is null
at playtime-1.11.6.jar//nl.thedutchruben.playtime.extentions.PlaceholderAPIExpansion.onPlaceholderRequest(PlaceholderAPIExpansion.java:33)
at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32)
at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
at InteractiveChat-4.2.6.1.jar//com.loohp.interactivechat.utils.PlaceholderParser.parse0(PlaceholderParser.java:104)
at InteractiveChat-4.2.6.1.jar//com.loohp.interactivechat.utils.PlaceholderParser.parse(PlaceholderParser.java:83)
at InteractiveChat-4.2.6.1.jar//com.loohp.interactivechat.modules.PlayernameDisplay.processPlayer(PlayernameDisplay.java:104)
at InteractiveChat-4.2.6.1.jar//com.loohp.interactivechat.modules.PlayernameDisplay.process(PlayernameDisplay.java:85)
at InteractiveChat-4.2.6.1.jar//com.loohp.interactivechat.listeners.OutMessagePacket.processPacket(OutMessagePacket.java:599)
at InteractiveChat-4.2.6.1.jar//com.loohp.interactivechat.listeners.OutMessagePacket.access$200(OutMessagePacket.java:84)
at InteractiveChat-4.2.6.1.jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.lambda$onPacketSending$0(OutMessagePacket.java:484)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by LOOHP** [comment]
This is an error due to your playtime plugin's papi placeholder not supporting offline calls.
