### ISSUE TITLE
Console error when someone mentions and text with UUID appears in chat

### ISSUE THREAD

**Issue by jefflima1** [LOOHP/InteractiveChat#154]
[02:08:13 INFO]: [Not Secure] <[NMiner] zCarrosIrados> jeffl1ma
[02:08:13 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.loohp.interactivechat.utils.ToastUtils.nmsAdvancementConstructor" is null
[02:08:13 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.utils.ToastUtils.mention(ToastUtils.java:124)
[02:08:13 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.modules.MentionDisplay.process(MentionDisplay.java:169)
[02:08:13 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket.processPacket(OutMessagePacket.java:605)
[02:08:13 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket.access$200(OutMessagePacket.java:84)
[02:08:13 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.lambda$onPacketSending$0(OutMessagePacket.java:484)
[02:08:13 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[02:08:13 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[02:08:13 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[02:08:13 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[02:08:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

![image](https://github.com/LOOHP/InteractiveChat/assets/106811319/d5fe0165-3322-460d-976f-b632c18c038a)

**Comment by LOOHP** [comment]
Fixed in 4.2.7.1
