### ISSUE TITLE
Mention doesn't work on 1.20.1

### ISSUE THREAD

**Issue by MiSa-JD** [LOOHP/InteractiveChat#155]
I can't use mention on my paper 20 1.20.1 server.

When I use mention, <chat=(caller's uuid):IC^@(reciever):> was displayed on chat, and the error code is shown in the console

```
[14:07:10 INFO]: [Not Secure] <dlatl001> @4NY7H1NG
[14:07:10 WARN]: java.lang.IllegalArgumentException: Attempt to get net.minecraft.server.level.PlayerInteractManager field "net.minecraft.server.level.EntityPlayer.e" wi
th illegal data type conversion to int
[14:07:10 WARN]:        at java.base/jdk.internal.reflect.FieldAccessorImpl.newGetIllegalArgumentException(FieldAccessorImpl.java:130)
[14:07:10 WARN]:        at java.base/jdk.internal.reflect.FieldAccessorImpl.newGetIntIllegalArgumentException(FieldAccessorImpl.java:193)
[14:07:10 WARN]:        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.getInt(MethodHandleObjectFieldAccessorImpl.java:84)
[14:07:10 WARN]:        at java.base/java.lang.reflect.Field.getInt(Field.java:614)
[14:07:10 WARN]:        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:66)
[14:07:10 WARN]:        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:50)
[14:07:10 WARN]:        at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:122)
[14:07:10 WARN]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:481)
[14:07:10 WARN]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:405)
[14:07:10 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[14:07:10 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[14:07:10 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[14:07:10 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.utils.PlaceholderParser.parse0(PlaceholderParser.java:104)
[14:07:10 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.utils.PlaceholderParser.parse(PlaceholderParser.java:83)
[14:07:10 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.modules.PlayernameDisplay.processPlayer(PlayernameDisplay.java:104)
[14:07:10 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.modules.PlayernameDisplay.process(PlayernameDisplay.java:85)
[14:07:10 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket.processPacket(OutMessagePacket.java:599)
[14:07:10 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket.access$200(OutMessagePacket.java:84)
[14:07:10 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.lambda$onPacketSending$0(OutMessagePacket.java:484)
[14:07:10 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[14:07:10 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[14:07:10 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:07:10 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[14:07:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[14:07:10 WARN]: java.lang.IllegalArgumentException: Attempt to get net.minecraft.server.level.PlayerInteractManager field "net.minecraft.server.level.EntityPlayer.e" with illegal data type conversion to int
[14:07:10 WARN]:        at java.base/jdk.internal.reflect.FieldAccessorImpl.newGetIllegalArgumentException(FieldAccessorImpl.java:130)
[14:07:10 WARN]:        at java.base/jdk.internal.reflect.FieldAccessorImpl.newGetIntIllegalArgumentException(FieldAccessorImpl.java:193)
[14:07:10 WARN]:        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.getInt(MethodHandleObjectFieldAccessorImpl.java:84)
[14:07:10 WARN]:        at java.base/java.lang.reflect.Field.getInt(Field.java:614)
[14:07:10 WARN]:        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:66)
[14:07:10 WARN]:        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:50)
[14:07:10 WARN]:        at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:122)
[14:07:10 WARN]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:481)
[14:07:10 WARN]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:405)
[14:07:10 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[14:07:10 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[14:07:10 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[14:07:10 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.utils.PlaceholderParser.parse0(PlaceholderParser.java:104)
[14:07:10 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.utils.PlaceholderParser.parse(PlaceholderParser.java:83)
[14:07:10 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.modules.PlayernameDisplay.processPlayer(PlayernameDisplay.java:104)
[14:07:10 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.modules.PlayernameDisplay.process(PlayernameDisplay.java:85)
[14:07:10 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket.processPacket(OutMessagePacket.java:599)
[14:07:10 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket.access$200(OutMessagePacket.java:84)
[14:07:10 WARN]:        at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.lambda$onPacketSending$0(OutMessagePacket.java:484)
[14:07:10 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[14:07:10 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[14:07:10 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:07:10 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[14:07:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by LOOHP** [comment]
You need to update your Papi Player Expansion
