### ISSUE TITLE
1.20.1 stacktrace

### ISSUE THREAD

**Issue by xsmeths** [LOOHP/InteractiveChat#157]
```
[21:31:49] [Craft Scheduler Thread - 8 - InteractiveChat/WARN]: [InteractiveChat] Plugin InteractiveChat v4.2.7.1 generated an exception while executing task 33
java.lang.IllegalArgumentException: Attempt to get net.minecraft.server.level.PlayerInteractManager field "net.minecraft.server.level.EntityPlayer.e" with illegal data type conversion to int
	at jdk.internal.reflect.UnsafeFieldAccessorImpl.newGetIllegalArgumentException(UnsafeFieldAccessorImpl.java:69) ~[?:?]
	at jdk.internal.reflect.UnsafeFieldAccessorImpl.newGetIntIllegalArgumentException(UnsafeFieldAccessorImpl.java:132) ~[?:?]
	at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.getInt(UnsafeQualifiedObjectFieldAccessorImpl.java:59) ~[?:?]
	at java.lang.reflect.Field.getInt(Field.java:601) ~[?:?]
	at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:66) ~[?:?]
	at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:50) ~[?:?]
	at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:122) ~[?:?]
	at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:471) ~[?:?]
	at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:395) ~[?:?]
	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.2.jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.2.jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[PlaceholderAPI-2.11.2.jar:?]
	at com.loohp.interactivechat.utils.PlaceholderParser.getAllPlaceholdersContained(PlaceholderParser.java:119) ~[InteractiveChat-4.2.7.1.jar:?]
	at com.loohp.interactivechat.utils.PlaceholderParser.parse0(PlaceholderParser.java:95) ~[InteractiveChat-4.2.7.1.jar:?]
	at com.loohp.interactivechat.utils.PlaceholderParser.parse(PlaceholderParser.java:83) ~[InteractiveChat-4.2.7.1.jar:?]
	at com.loohp.interactivechat.InteractiveChat.lambda$onEnable$1(InteractiveChat.java:462) ~[InteractiveChat-4.2.7.1.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-63]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-63]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
Paper 1.20.1 - build 63
InteractiveChat-4.2.7.2
Protocollib Build #660

**Comment by cupangafk** [comment]
same here

```
[23:24:46 WARN]: java.lang.IllegalArgumentException: Attempt to get net.minecraft.server.level.PlayerInteractManager field "net.minecraft.server.level.EntityPlayer.e" with illegal data type conversion to int
[23:24:46 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.newGetIllegalArgumentException(UnsafeFieldAccessorImpl.java:69)
[23:24:46 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.newGetIntIllegalArgumentException(UnsafeFieldAccessorImpl.java:132)
[23:24:46 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.getInt(UnsafeQualifiedObjectFieldAccessorImpl.java:59)
[23:24:46 WARN]:        at java.base/java.lang.reflect.Field.getInt(Field.java:601)
[23:24:46 WARN]:        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:66)
[23:24:46 WARN]:        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:50)
[23:24:46 WARN]:        at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:122)
[23:24:46 WARN]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:481)
[23:24:46 WARN]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:403)
[23:24:46 WARN]:        at PlaceholderAPI-LATEST-[2.11.3].jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[23:24:46 WARN]:        at PlaceholderAPI-LATEST-[2.11.3].jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[23:24:46 WARN]:        at PlaceholderAPI-LATEST-[2.11.3].jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[23:24:46 WARN]:        at InteractiveChat-[Jenkins-230].jar//com.loohp.interactivechat.utils.PlaceholderParser.parse0(PlaceholderParser.java:104)
[23:24:46 WARN]:        at InteractiveChat-[Jenkins-230].jar//com.loohp.interactivechat.utils.PlaceholderParser.parse(PlaceholderParser.java:83)
[23:24:46 WARN]:        at InteractiveChat-[Jenkins-230].jar//com.loohp.interactivechat.modules.PlayernameDisplay.processPlayer(PlayernameDisplay.java:104)
[23:24:46 WARN]:        at InteractiveChat-[Jenkins-230].jar//com.loohp.interactivechat.modules.PlayernameDisplay.process(PlayernameDisplay.java:85)
[23:24:46 WARN]:        at InteractiveChat-[Jenkins-230].jar//com.loohp.interactivechat.listeners.OutMessagePacket.processPacket(OutMessagePacket.java:599)
[23:24:46 WARN]:        at InteractiveChat-[Jenkins-230].jar//com.loohp.interactivechat.listeners.OutMessagePacket.access$200(OutMessagePacket.java:84)
[23:24:46 WARN]:        at InteractiveChat-[Jenkins-230].jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.lambda$onPacketSending$0(OutMessagePacket.java:484)
[23:24:46 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[23:24:46 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[23:24:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:24:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:24:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

```
[23:27:59 INFO]: Checking version, please wait...
[23:28:00 INFO]: Current: git-Purpur-2014 (MC: 1.20.1)*
Previous: git-Purpur-2004 (MC: 1.20.1)
* You are running the latest version
```

InteractiveChat jenkins build [#230](https://ci.loohpjames.com/job/InteractiveChat/230/)

**Comment by cupangafk** [comment]
updating [player placeholder api expansion](https://api.extendedclip.com/expansions/player/) seems fix my issue (probably caused by %player_ping%)

**Comment by HollishKid** [comment]
This error still exists on 1.20.4:

```
[13:20:11 WARN]: [InteractiveChat] Plugin InteractiveChat v4.2.9.0 generated an exception while executing task 4421
java.lang.IllegalArgumentException: Unexpected type: class io.papermc.paper.adventure.AdventureComponent
        at com.loohp.interactivechat.utils.PlayerUtils.chatAsPlayer(PlayerUtils.java:197) ~[InteractiveChat-4.2.9.0.jar:?]
        at com.loohp.interactivechat.listeners.RedispatchSignedPacket$1.lambda$onPacketReceiving$4(RedispatchSignedPacket.java:92) ~[InteractiveChat-4.2.9.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-497]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

This happens whenever I type something in chat.

For reference:
```
System Info: Java 21 (OpenJDK 64-Bit Server VM 21.0.2+13-LTS) Host: Windows 10 10.0 (amd64)
This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)
```

**Comment by IsNott** [comment]
> updating [player placeholder api expansion](https://api.extendedclip.com/expansions/player/) seems fix my issue (probably caused by %player_ping%)

It works,put the expansions jar into minecraft-Path/plugins/PlaceholderAPI/expansions fix.
