### ISSUE TITLE
Mentioning someone results to error

### ISSUE THREAD

**Issue by PRO-2684** [LOOHP/InteractiveChat#166]
The sender and other players can see the mention normally, but the one mentioned will see `<chat=...:<IC^@xxx>:>` instead of `@xxx`.

Console log:

```
[13:55:50] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.loohp.interactivechat.utils.ToastUtils.nmsAdvancementConstructor" is null
[13:55:50] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]:       at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.utils.ToastUtils.mention(ToastUtils.java:124)
[13:55:50] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]:       at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.modules.MentionDisplay.process(MentionDisplay.java:169)
[13:55:50] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]:       at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket.processPacket(OutMessagePacket.java:605)
[13:55:50] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]:       at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket.access$200(OutMessagePacket.java:84)
[13:55:50] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]:       at InteractiveChat-4.2.7.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.lambda$onPacketSending$0(OutMessagePacket.java:484)
[13:55:50] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]:       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[13:55:50] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]:       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[13:55:50] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[13:55:50] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:55:50] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by zefir-git** [comment]
Had the same problem, except for me `nmsCriterionConstructor` was null

**Comment by dortik98** [comment]
same problem

**Comment by onlive1337** [comment]
has anyone fixed it?
