### ISSUE TITLE
Error with using on Velocity with HuskChat

### ISSUE THREAD

**Issue by LittleBigBug** [LOOHP/InteractiveChat#181]
When using HuskChat and SignedVelocity on my proxy, every player message results in this:

```
[huskchat]: [CHAT] [GLOBAL] player: message
[15:51:37 ERROR]: java.lang.RuntimeException: There is an error when converting to native adventure components
[15:51:37 ERROR]:       at com.loohp.interactivechat.utils.NativeAdventureConverter.error(NativeAdventureConverter.java:160)
[15:51:37 ERROR]:       at com.loohp.interactivechat.utils.NativeAdventureConverter.jsonStringFromNative(NativeAdventureConverter.java:184)
[15:51:37 ERROR]:       at com.loohp.interactivechat.proxy.velocity.InteractiveChatVelocity$2.write(InteractiveChatVelocity.java:893)
[15:51:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[15:51:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[15:51:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247)
[15:51:37 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[15:51:37 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[15:51:37 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[15:51:37 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[15:51:37 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[15:51:37 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:51:37 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[15:51:37 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:840)
[15:51:37 ERROR]: Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@3fcd052c
[15:51:37 ERROR]:       at jdk.internal.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
[15:51:37 ERROR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:51:37 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[15:51:37 ERROR]:       at com.loohp.interactivechat.utils.NativeAdventureConverter.jsonStringFromNative(NativeAdventureConverter.java:182)
[15:51:37 ERROR]:       ... 12 more

(trace repeats several times)
```

Using [item] also does not work and shows text like `<chat=78897d9asd98a...:[item]:>`

**Comment by FZnachor** [comment]
I'm having the same issues with the Carbon chat plugin on the Velocity proxy, so it's probably not specific to the plugins mentioned.

**Comment by dentatar** [comment]
I'm also having issues with HuskChat 3.X, no SignedVelocity installed, only PAPIProxyBridge. [item] is just red and showing "unable to parse placeholder" on hover, other things such as [pos] does not work at all… No errors in console either 🤔 Tried every priority with no luck… Everything works fine tho without HuskChat installed, so my InteractiveChat setup is correct
