### ISSUE TITLE
InteractiveChat-4.2.9.0 in velocity-3.3.0 Error reported when player enters server

### ISSUE THREAD

**Issue by lipind** [LOOHP/InteractiveChat#184]
java.lang.NoSuchMethodError: 'java.lang.String com.velocitypowered.proxy.protocol.packet.title.LegacyTitlePacket.getComponent()'
[22:04:43 ERROR]:       at com.loohp.interactivechat.proxy.velocity.InteractiveChatVelocity$2.write(InteractiveChatVelocity.java:908)
[22:04:43 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[22:04:43 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[22:04:43 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[22:04:43 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[22:04:43 ERROR]:       at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[22:04:43 ERROR]:       at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[22:04:43 ERROR]:       at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:248)
[22:04:43 ERROR]:       at com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler.handleBackendJoinGame(ClientPlaySessionHandler.java:555)
[22:04:43 ERROR]:       at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.lambda$handle$0(TransitionSessionHandler.java:134)
[22:04:43 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
[22:04:43 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[22:04:43 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[22:04:43 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)

[22:04:43 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[22:04:43 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[22:04:43 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[22:04:43 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[22:04:43 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[22:04:43 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by lipind** [comment]
I just found out that variables such as [inv] on the server seem to be unable to run due to this error on velocity- 3.3.0

**Comment by lipind** [comment]
yes,I use IC-4.2.9 ,  Velocity-3.3.0

I tested and found that it cannot be used because it is not compatible with my newly installed cross server chat，sorry

**Comment by LOOHP** [comment]
Do you mind downloading the latest dev build on ci.loohpjames.com and see if anything changes? Even though your version number is the latest the build might not.

**Comment by lipind** [comment]
latest dev build还是会在玩家进入时报错
 latest dev build还是会在玩家进入时报错
Late dev build still reports errors when players enter

**Comment by lipind** [comment]
java.lang.NullPointerException: Cannot invoke "com.velocitypowered.proxy.protocol.packet.chat.ComponentHolder.getJson()" because "holder" is null
[22:07:06 ERROR]:       at com.loohp.interactivechat.proxy.velocity.InteractiveChatVelocity$2.write(InteractiveChatVelocity.java:933)
[22:07:06 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[22:07:06 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[22:07:06 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[22:07:06 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[22:07:06 ERROR]:       at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[22:07:06 ERROR]:       at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[22:07:06 ERROR]:       at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:248)
[22:07:06 ERROR]:       at com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler.handleBackendJoinGame(ClientPlaySessionHandler.java:555)
[22:07:06 ERROR]:       at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.lambda$handle$0(TransitionSessionHandler.java:134)
[22:07:06 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
[22:07:06 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[22:07:06 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[22:07:06 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)

[22:07:06 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[22:07:06 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[22:07:06 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[22:07:06 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[22:07:06 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[22:07:06 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
