### ISSUE TITLE
Error while initiatlizing latest version on bungee.

### ISSUE THREAD

**Issue by andrewkm** [LOOHP/InteractiveChat#19]
Using Build 3.2.8.1
https://ci.loohpjames.com/job/InteractiveChat/103/

Getting the below in our Bungee console on proxy start.

```
[10:59:47] [Thread-38/ERROR]: Exception in thread "Thread-38" java.lang.NullPointerException
[10:59:47] [Thread-38/ERROR]: 	at com.loohp.interactivechat.Bungee.ServerPingBungee$1.run(ServerPingBungee.java:89)
[10:59:47] [Thread-38/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[10:59:47] [Thread-36/ERROR]: Exception in thread "Thread-36" Exception in thread "Thread-41" Exception in thread "Thread-34" java.lang.NullPointerException
[10:59:47] [Thread-36/ERROR]: Exception in thread "Thread-39" 	at com.loohp.interactivechat.Bungee.ServerPingBungee$1.run(ServerPingBungee.java:89)
[10:59:47] [Thread-36/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[10:59:47] [Thread-39/ERROR]: java.lang.NullPointerException
[10:59:47] [Thread-39/ERROR]: 	at com.loohp.interactivechat.Bungee.ServerPingBungee$1.run(ServerPingBungee.java:89)
[10:59:47] [Thread-39/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[10:59:47] [Thread-34/ERROR]: java.lang.NullPointerException
[10:59:47] [Thread-34/ERROR]: 	at com.loohp.interactivechat.Bungee.ServerPingBungee$1.run(ServerPingBungee.java:89)
[10:59:47] [Thread-34/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[10:59:47] [Thread-41/ERROR]: java.lang.NullPointerException
[10:59:47] [Thread-41/ERROR]: 	at com.loohp.interactivechat.Bungee.ServerPingBungee$1.run(ServerPingBungee.java:89)
[10:59:47] [Thread-41/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[10:59:47] [Thread-35/ERROR]: Exception in thread "Thread-35" java.lang.NullPointerException
[10:59:47] [Thread-35/ERROR]: 	at com.loohp.interactivechat.Bungee.ServerPingBungee$1.run(ServerPingBungee.java:89)
[10:59:47] [Thread-35/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[10:59:47] [Thread-40/ERROR]: Exception in thread "Thread-40" java.lang.NullPointerException
[10:59:47] [Thread-40/ERROR]: Exception in thread "Thread-37" 	at com.loohp.interactivechat.Bungee.ServerPingBungee$1.run(ServerPingBungee.java:89)
[10:59:47] [Thread-40/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[10:59:47] [Thread-37/ERROR]: java.lang.NullPointerException
[10:59:47] [Thread-37/ERROR]: 	at com.loohp.interactivechat.Bungee.ServerPingBungee$1.run(ServerPingBungee.java:89)
[10:59:47] [Thread-37/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by LOOHP** [comment]
Are you using the exact same version (dev builds are different versions as well) of InteractiveChat on bungee and all spigot/bukkit backend servers?

**Comment by andrewkm** [comment]
Nope, I'm just about to do that as I'm in the middle of a maintenance, I was 95% positive that's the issue but posted here to make sure lol. Will report back when done :)

**Comment by andrewkm** [comment]
This is indeed fixed once all correct versions are on the backend server.
Thank you for your quick responses!
