### ISSUE TITLE
Plugin stop working under Paper with CB packge relocation 

### ISSUE THREAD

**Issue by YuanYuanOwO** [LOOHP/InteractiveChat#195]
https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/

```
[20:07:50 INFO]: [InteractiveChat] This version of minecraft is unsupported! (Unsupported)
[20:07:50 INFO]: [InteractiveChat] Opened Sqlite database successfully
[20:07:50 ERROR]: Error occurred while enabling InteractiveChat v4.2.9.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.loohp.interactivechat.InteractiveChat.onEnable(InteractiveChat.java:517) ~[InteractiveChat-4.2.9.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1133) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at com.loohp.interactivechat.utils.NMSUtils.getNMSClass(NMSUtils.java:30) ~[InteractiveChat-4.2.9.0.jar:?]
        at com.loohp.interactivechat.utils.PlayerUtils.<clinit>(PlayerUtils.java:80) ~[InteractiveChat-4.2.9.0.jar:?]
        ... 13 more
[20:07:50 INFO]: [InteractiveChat] Disabling InteractiveChat v4.2.9.0
[20:07:50 ERROR]: Error occurred while disabling InteractiveChat v4.2.9.0
java.lang.ExceptionInInitializerError: null
        at com.comphenix.protocol.injector.StructureCache.initTrickDataSerializer(StructureCache.java:164) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.tryInitTrickDataSerializer(StructureCache.java:208) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.lambda$newPacket$3(StructureCache.java:72) ~[ProtocolLib.jar:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:64) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:113) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:117) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.createPacket(PacketFilterManager.java:389) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.createPacket(PacketFilterManager.java:384) ~[ProtocolLib.jar:?]
        at com.loohp.interactivechat.listeners.OutMessagePacket.<clinit>(OutMessagePacket.java:277) ~[InteractiveChat-4.2.9.0.jar:?]
        at com.loohp.interactivechat.InteractiveChat.onDisable(InteractiveChat.java:687) ~[InteractiveChat-4.2.9.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1133) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:143) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedChatComponent.<clinit>(WrappedChatComponent.java:49) ~[ProtocolLib.jar:?]
        ... 26 more
```

**Comment by LOOHP** [comment]
Should be addressed in 4.2.10.
