### ISSUE TITLE
[1.20.4] LPC + InteractiveChat Error

### ISSUE THREAD

**Issue by FaultyFunctions** [LOOHP/InteractiveChat#217]
Hello! When using the default chat format in LPC the chat works fine, but when I switch to a group specific chat format the message doesn't come through and InteractiveChat gives an error in the console.

Here is the error:
```
[23:27:37 WARN]: [InteractiveChat] Plugin InteractiveChat v4.2.10.0 generated an exception while executing task 3638
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at de.ayont.lpc.renderer.LPCChatRenderer.render(LPCChatRenderer.java:99) ~[LPC-Minimessage-3.6.4.jar:?]
        at io.papermc.paper.adventure.ChatProcessor$ViewersOutgoingChat.lambda$sendFormatChangedViewerAware$0(ChatProcessor.java:242) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.adventure.ChatProcessor$ViewersOutgoingChat.sendToServer(ChatProcessor.java:319) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.adventure.ChatProcessor$ViewersOutgoingChat.sendNative(ChatProcessor.java:308) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.adventure.ChatProcessor$ViewersOutgoingChat.broadcastToViewers(ChatProcessor.java:258) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.adventure.ChatProcessor$ViewersOutgoingChat.sendFormatChangedViewerAware(ChatProcessor.java:242) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.adventure.ChatProcessor.complete(ChatProcessor.java:197) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.adventure.ChatProcessor.processModern(ChatProcessor.java:167) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:106) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2389) ~[?:?]
        at com.loohp.interactivechat.nms.V1_20_3.chatAsPlayerAsync(V1_20_3.java:494) ~[InteractiveChat-4.2.10.0.jar:?]
        at com.loohp.interactivechat.utils.PlayerUtils.chatAsPlayer(PlayerUtils.java:75) ~[InteractiveChat-4.2.10.0.jar:?]
        at com.loohp.interactivechat.listeners.RedispatchSignedPacket$1.lambda$onPacketReceiving$3(RedispatchSignedPacket.java:85) ~[InteractiveChat-4.2.10.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Let me know if you need more information, thanks!

**Comment by TheSteveRizzo** [comment]
+1 Also having the issue specific to LPC + InteractiveChat (where group prefixes will show not formatted or unprocessed) when using group formatting; I also use ItemsAdder which processes a prefix text to an image

**Comment by LOOHP** [comment]
Are you sure it only happens when InteractiveChat is installed?

**Comment by TheSteveRizzo** [comment]
Hi, thanks for the quick reply. For instance in LPC I have a prefix set as “:member:” which gets replaced with an ItemsAdder image. Unfortunately when InteractiveChat is enabled, the message sends before processing the other placeholder and appears as raw text (I.e., “:member:”, not an image). I’ve adjusted the priority settings from LOWEST to HIGHEST and MONITOR but I’ve come to the conclusion for now LPC chat formatting has some sort of issue when I use this, which is a shame because it has so many cool features!
Please advise.

**Comment by FaultyFunctions** [comment]
@TheSteveRizzo I've since switched to a plugin called ChatFormatter. It works flawlessly for me and has pretty much the same simplicity as LPC. https://www.spigotmc.org/resources/%EF%B8%8F-chatformatter-✔%EF%B8%8F-beautify-your-chat-with-hovers-clickable-messages-and-more.102212/
