### ISSUE TITLE
Possible Duplication With Some Slimefun Items (Compatibility)

### ISSUE THREAD

**Issue by variananora** [LOOHP/InteractiveChat#22]
There is a possible duplication with some Slimefun items.

EDIT: Works with furnace based item, hopper based item, and smoker based item.

Replication method:
  1. Get a Slimefun item, (works better with furnaces?)
  2. Share inventory on chat
  3. You, or someone else take that item from chat
  4. Dupe is possible.

Proof:
https://youtu.be/iIubibDwi_U

Server Version: 1.16.5 (Tuinity-d3ee222)
Interactive Chat Version: 3.2.8.0
Relevant Plugins: Slimefun DEV-801

**Comment by LOOHP** [comment]
I already cancelled the InventoryClickEvent early on in the process. Perhaps you would want SlimFun to not ignore that. I can still see if there is anything I could do if they are unwilling to move.

**Comment by LOOHP** [comment]
InteractiveChat cancels both early and late in the InventoryClickEvent so it's probably due to other plugins not respect the Inventory Event getting cancelled. Perhaps you can ask SlimeFun developers to take a look on their end?

**Comment by variananora** [comment]
> Perhaps you can ask SlimeFun developers to take a look on their end?
Will do, I'll tell you the update later.

**Comment by Hellcode48** [comment]
Same problem with slimefun, getting this tho:

java.lang.IllegalArgumentException: Size for custom inventory must be a multiple of 9 between 9 and 54 slots (got 12)
at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.16.5.jar:git-Paper-457]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createInventory(CraftServer.java:1815) ~[patched_1.16.5.jar:git-Paper-457]
at org.bukkit.Bukkit.createInventory(Bukkit.java:1181) ~[patched_1.16.5.jar:git-Paper-457]
at com.loohp.interactivechat.Listeners.Events.onInventoryClick(Events.java:315) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1964.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-457]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-457]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-457]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2540) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1200) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-457]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-457]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by LOOHP** [comment]
Give the latest dev build a try (3.2.9.5), I made some changes that might work.

**Comment by variananora** [comment]
> Give the latest dev build a try (3.2.9.5), I made some changes that might work.

Still the same results.

**Comment by TheBusyBiscuit** [comment]
I am not really sure how this issue could be caused, especially because it seems to only affect certain items?

We don't mess with the `InventoryClickEvent` unless the inventory was created by us specifically.
And even there we don't have any segregations between item types. So this is all very strange to me.
Not sure why the report was made on the "CS-CoreLib2" repository either...

But I conducted some research and found this portion of the code:
https://github.com/LOOHP/InteractiveChat/blob/master/src/main/java/com/loohp/interactivechat/Listeners/Events.java#L311-L337

All of these items have one thing in common: They have a `BlockStateMeta`.
So if an exception were to happen in this part of the code, `event.setCancelled(true);` would never be reached. Nor would the `cancelledInventory.add(event);` line of code be reached. Which in turn doesn't trigger the second event.

@LOOHP Side note: I'd suggest you to utilize try/catches for this code and print some error context just in case something goes wrong, like the clicked material and stuff. Proper error handling would also allow you to cancel the event even in the event of an exception being thrown.

@variananora Are you sure there was no stacktrace in your console when clicking these items?

**Comment by variananora** [comment]
> Not sure why the report was made on the "CS-CoreLib2" repository either...

I thought it was some compability issues posted on CSCL.

> @variananora Are you sure there was no stacktrace in your console when clicking these items?
My bad, when I posted this I forgot to send the link, and just wrote nothing.

With InteractiveChat 3.2.8.0-3.2.9.5:
https://haste.zneix.eu/aretefujaq.vbs
With InteractiveChat 3.2.9.6:
https://haste.zneix.eu/acobekoxez.vbs

**Comment by TheBusyBiscuit** [comment]
@LOOHP For some reason there is a mod-zero operation here which will result in an `ArithmeticException`
https://github.com/LOOHP/InteractiveChat/blob/master/src/main/java/com/loohp/interactivechat/Listeners/Events.java#L315
I think this was supposed to be a 9 and you wanted to see if the inventory size was a multiple of 9 then?
Since mod-zero is mathematically undefined.
I think some error handling would benefit future issues like this a lot.

I assume that this is the cause of this issue.
I'll wait for feedback and then close the CSCL2-issue afterwards.

Anyway, this does look like an interesting plugin though :)

**Comment by LOOHP** [comment]
> I am not really sure how this issue could be caused, especially because it seems to only affect certain items?
> 
> We don't mess with the `InventoryClickEvent` unless the inventory was created by us specifically.
> And even there we don't have any segregations between item types. So this is all very strange to me.
> Not sure why the report was made on the "CS-CoreLib2" repository either...
> 
> But I conducted some research and found this portion of the code:
> https://github.com/LOOHP/InteractiveChat/blob/master/src/main/java/com/loohp/interactivechat/Listeners/Events.java#L311-L337
> 
> All of these items have one thing in common: They have a `BlockStateMeta`.
> So if an exception were to happen in this part of the code, `event.setCancelled(true);` would never be reached. Nor would the `cancelledInventory.add(event);` line of code be reached. Which in turn doesn't trigger the second event.
> 
> @LOOHP Side note: I'd suggest you to utilize try/catches for this code and print some error context just in case something goes wrong, like the clicked material and stuff. Proper error handling would also allow you to cancel the event even in the event of an exception being thrown.
> 
> @variananora Are you sure there was no stacktrace in your console when clicking these items?

> @LOOHP For some reason there is a mod-zero operation here which will result in an `ArithmeticException`
> https://github.com/LOOHP/InteractiveChat/blob/master/src/main/java/com/loohp/interactivechat/Listeners/Events.java#L315
> I think this was supposed to be a 9 and you wanted to see if the inventory size was a multiple of 9 then?
> Since mod-zero is mathematically undefined.
> I think some error handling would benefit future issues like this a lot.
> 
> I assume that this is the cause of this issue.
> I'll wait for feedback and then close the CSCL2-issue afterwards.
> 
> Anyway, this does look like an interesting plugin though :)

Ah, you are right, I mistyped 9 into a 0 oops...
I'll also be moving the event cancelling as high up as possible in case of errors.

Releasing a dev build right now.

**Comment by variananora** [comment]
Update on this:
It seems like it just broke with some renamed item (tested with hopper, smoker, and furnace) with inventory on it?
Video: 

https://user-images.githubusercontent.com/34732414/106455952-7d616c80-64bf-11eb-988d-83e9cc4a5058.mp4

With the same log like before:
> With InteractiveChat 3.2.8.0-3.2.9.5:
> https://haste.zneix.eu/aretefujaq.vbs
> With InteractiveChat 3.2.9.6:
> https://haste.zneix.eu/acobekoxez.vbs

> I'll wait for feedback and then close the CSCL2-issue afterwards.

I think this is InteractiveChat's issue and not Slimefun nor CSCL2. I'll close it there.

**Comment by variananora** [comment]
Fixed on version 3.2.9.7
