### ISSUE TITLE
DIfferent sessions API to prevent ratelimits from Mojang?

### ISSUE THREAD

**Issue by bobhenl** [LOOHP/InteractiveChat#230]
Hello, I'm getting ratelimited & I noticed that InteractiveChat is very often calling the sessions mojang API, maybe it can be replaced by another one? Not sure what it uses, but here are some alternatives:
```yml
Sat Aug 17 21:34:36 UTC 2024: Intercepted connection to sessionserver.mojang.com by plugin InteractiveChat
	at InteractiveChat-4.2.12.0.jar//com.loohp.interactivechat.utils.HTTPRequestUtils.getTextResponse(HTTPRequestUtils.java:74) [InteractiveChat]
	at InteractiveChat-4.2.12.0.jar//com.loohp.interactivechat.utils.HTTPRequestUtils.getJSONResponse(HTTPRequestUtils.java:50) [InteractiveChat]
	at InteractiveChat-4.2.12.0.jar//com.loohp.interactivechat.utils.SkinUtils.getSkinURLFromUUID(SkinUtils.java:83) [InteractiveChat]
	at InteractiveChatDiscordSrvAddon-4.2.12.0-1723901941308.jar//com.loohp.interactivechatdiscordsrvaddon.InteractiveChatDiscordSrvAddon.cachePlayerSkin(InteractiveChatDiscordSrvAddon.java:418) [InteractiveChatDiscordSrvAddon]
	at InteractiveChatDiscordSrvAddon-4.2.12.0-1723901941308.jar//com.loohp.interactivechatdiscordsrvaddon.InteractiveChatDiscordSrvAddon.lambda$onEnable$3(InteractiveChatDiscordSrvAddon.java:386) [InteractiveChatDiscordSrvAddon]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

https://eclipse.skinsrestorer.net/mojang/uuid/Pistonmaster
https://eclipse.skinsrestorer.net/mojang/skin/b1ae0778-4817-436c-96a3-a72c67cda060

https://eclipse.skinsrestorer.net/docs/

I believe it should be good, better than the Ashcon one https://api.ashcon.app/mojang/v2/user/

https://crafatar.com/skins/UUID
https://api.mineskin.org/generate/user/UUID

not sure why you all it, if it's due to heads, then maybe mineskin or so can be used instead?

Maybe there can be at least a way to change the API in config?

**Comment by bobhenl** [comment]
Anything that can be done about this, please @LOOHP ?
