### ISSUE TITLE
1.19.2 version sending messages error

### ISSUE THREAD

**Issue by homerek111** [LOOHP/InteractiveChat#236]
im getting this error on every single message i try to send and my messages are not being sent at all...
```
[07:37:49 WARN]: [InteractiveChat] Plugin InteractiveChat v4.2.12.0 generated an exception while executing task 5931
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "this.paperPlayerChatMessageWithResultMethod" is null
        at com.loohp.interactivechat.nms.V1_19.modernChatSigningWithResult(V1_19.java:443) ~[InteractiveChat-4.2.12.0.jar:?]
        at com.loohp.interactivechat.nms.V1_19.chatAsPlayerAsync(V1_19.java:504) ~[InteractiveChat-4.2.12.0.jar:?]
        at com.loohp.interactivechat.utils.PlayerUtils.chatAsPlayer(PlayerUtils.java:75) ~[InteractiveChat-4.2.12.0.jar:?]
        at com.loohp.interactivechat.listeners.RedispatchSignedPacket$1.lambda$onPacketReceiving$3(RedispatchSignedPacket.java:87) ~[InteractiveChat-4.2.12.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1768]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1768]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

server version:
```
Current: git-Purpur-1768 (MC: 1.19.2)
```

plugin version:
```
4.2.12.0
```

that's info from ``/icp backendinfo``
![obraz](https://github.com/user-attachments/assets/c95054c0-ec9e-4d4c-93f9-841b325e98e3)

all other servers work fine but this skyblock does not...

**Comment by homerek111** [comment]
@LOOHP any chance of fixing? :/

**Comment by homerek111** [comment]
@LOOHP 1.19.2 plugin breaks sending all messages - please fix :))

**Comment by homerek111** [comment]
@LOOHP pls fix that issue :/

**Comment by LOOHP** [comment]
Seems like the latest purpur build for 1.19.2 is #1858. Have you tried updating to that?

**Comment by homerek111** [comment]
> Seems like the latest purpur build for 1.19.2 is #1858. Have you tried updating to that?

I can try do it in a few hours when I get back home. I hope it won’t break anything on my server…

anyways this sending message bugs happens only with interactivechat so I believe it might be some issue on plugin’s side - however I can test it after updating to the latest 1.19.2 purpur and let you know…

**Comment by homerek111** [comment]
> Seems like the latest purpur build for 1.19.2 is #1858. Have you tried updating to that?

@LOOHP updating to the latest 1.19.2 build did not help :/
- could you please take a look at that issue from plugin's side?

![obraz](https://github.com/user-attachments/assets/50c52a43-4575-4768-8bf1-3d63ef0740ef)


```
[04:54:58 WARN]: [InteractiveChat] Plugin InteractiveChat v4.2.13.0 generated an exception while executing task 3050
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "this.paperPlayerChatMessageWithResultMethod" is null
        at com.loohp.interactivechat.nms.V1_19.modernChatSigningWithResult(V1_19.java:443) ~[InteractiveChat-4.2.13.0.jar:?]
        at com.loohp.interactivechat.nms.V1_19.chatAsPlayerAsync(V1_19.java:504) ~[InteractiveChat-4.2.13.0.jar:?]
        at com.loohp.interactivechat.utils.PlayerUtils.chatAsPlayer(PlayerUtils.java:75) ~[InteractiveChat-4.2.13.0.jar:?]
        at com.loohp.interactivechat.listeners.RedispatchSignedPacket$1.lambda$onPacketReceiving$3(RedispatchSignedPacket.java:87) ~[InteractiveChat-4.2.13.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
