### ISSUE TITLE
not display messages

### ISSUE THREAD

**Issue by TaTaLe** [LOOHP/InteractiveChat#242]
not display message
![QQ20241130-212348](https://github.com/user-attachments/assets/2d69a031-a8fb-4e6a-a077-7c28be81e862)
version：paper 1.12.2
InteractiveChat version：4.2.13

[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: java.lang.IllegalArgumentException: Attempt to get net.minecraft.server.v1_12_R1.EntityHuman$EnumChatVisibility field "net.minecraft.server.v1_12_R1.EntityPlayer.cl" with illegal data type conversion to boolean
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.newGetIllegalArgumentException(Unknown Source)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.newGetBooleanIllegalArgumentException(Unknown Source)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.getBoolean(Unknown Source)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at java.lang.reflect.Field.getBoolean(Unknown Source)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at com.loohp.interactivechat.nms.V1_12.canChatColor(V1_12.java:432)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at com.loohp.interactivechat.utils.PlayerUtils.canChatColor(PlayerUtils.java:162)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at com.loohp.interactivechat.listeners.OutMessagePacket.processPacket(OutMessagePacket.java:656)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at com.loohp.interactivechat.listeners.OutMessagePacket.access$300(OutMessagePacket.java:87)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at com.loohp.interactivechat.listeners.OutMessagePacket$1.lambda$onPacketSending$0(OutMessagePacket.java:499)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at java.lang.Thread.run(Unknown Source)

[20:30:37 WARN]: java.lang.NullPointerException: like
[20:30:37 WARN]:        at java.util.Objects.requireNonNull(Unknown Source)
[20:30:37 WARN]:        at com.loohp.interactivechat.libs.net.kyori.adventure.text.Component.append(Component.java:1994)
[20:30:37 WARN]:        at com.loohp.interactivechat.libs.net.kyori.adventure.text.ScopedComponent.append(ScopedComponent.java:83)
[20:30:37 WARN]:        at com.loohp.interactivechat.libs.net.kyori.adventure.text.Component.append(Component.java:1983)
[20:30:37 WARN]:        at com.loohp.interactivechat.libs.net.kyori.adventure.text.ScopedComponent.append(ScopedComponent.java:77)
[20:30:37 WARN]:        at com.loohp.interactivechat.utils.ItemStackUtils.getDisplayName(ItemStackUtils.java:54)
[20:30:37 WARN]:        at com.loohp.interactivechat.utils.ItemStackUtils.getDisplayName(ItemStackUtils.java:44)
[20:30:37 WARN]:        at com.loohp.interactivechat.utils.ItemStackUtils.getDisplayName(ItemStackUtils.java:40)
[20:30:37 WARN]:        at com.loohp.interactivechat.modules.ItemDisplay.createItemDisplay(ItemDisplay.java:207)
[20:30:37 WARN]:        at com.loohp.interactivechat.modules.ItemDisplay.createItemDisplay(ItemDisplay.java:157)
[20:30:37 WARN]:        at com.loohp.interactivechat.modules.ItemDisplay.process(ItemDisplay.java:99)
[20:30:37 WARN]:        at com.loohp.interactivechat.listeners.OutMessagePacket.processPacket(OutMessagePacket.java:635)
[20:30:37 WARN]:        at com.loohp.interactivechat.listeners.OutMessagePacket.access$300(OutMessagePacket.java:87)
[20:30:37 WARN]:        at com.loohp.interactivechat.listeners.OutMessagePacket$1.lambda$onPacketSending$0(OutMessagePacket.java:499)
[20:30:37 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:30:37 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[20:30:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:30:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:30:37 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:30:37 WARN]: java.lang.NullPointerException: like
[20:30:37 WARN]:        at java.util.Objects.requireNonNull(Unknown Source)
[20:30:37 WARN]:        at com.loohp.interactivechat.libs.net.kyori.adventure.text.Component.append(Component.java:1994)
[20:30:37 WARN]:        at com.loohp.interactivechat.libs.net.kyori.adventure.text.ScopedComponent.append(ScopedComponent.java:83)
[20:30:37 WARN]:        at com.loohp.interactivechat.libs.net.kyori.adventure.text.Component.append(Component.java:1983)
[20:30:37 WARN]:        at com.loohp.interactivechat.libs.net.kyori.adventure.text.ScopedComponent.append(ScopedComponent.java:77)
[20:30:37 WARN]:        at com.loohp.interactivechat.utils.ItemStackUtils.getDisplayName(ItemStackUtils.java:54)
[20:30:37 WARN]:        at com.loohp.interactivechat.utils.ItemStackUtils.getDisplayName(ItemStackUtils.java:44)
[20:30:37 WARN]:        at com.loohp.interactivechat.utils.ItemStackUtils.getDisplayName(ItemStackUtils.java:40)
[20:30:37 WARN]:        at com.loohp.interactivechat.modules.ItemDisplay.createItemDisplay(ItemDisplay.java:207)
[20:30:37 WARN]:        at com.loohp.interactivechat.modules.ItemDisplay.createItemDisplay(ItemDisplay.java:157)
[20:30:37 WARN]:        at com.loohp.interactivechat.modules.ItemDisplay.process(ItemDisplay.java:99)
[20:30:37 WARN]:        at com.loohp.interactivechat.listeners.OutMessagePacket.processPacket(OutMessagePacket.java:635)
[20:30:37 WARN]:        at com.loohp.interactivechat.listeners.OutMessagePacket.access$300(OutMessagePacket.java:87)
[20:30:37 WARN]:        at com.loohp.interactivechat.listeners.OutMessagePacket$1.lambda$onPacketSending$0(OutMessagePacket.java:499)
[20:30:37 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:30:37 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[20:30:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:30:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:30:37 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by TaTaLe** [comment]
[20:41:52 ERROR]: [InteractiveChat] Unhandled exception occurred in onPacketReceiving(PacketEvent) for InteractiveChat
java.lang.IllegalArgumentException: Attempt to get net.minecraft.server.v1_12_R1.EntityHuman$EnumChatVisibility field "net.minecraft.server.v1_12_R1.EntityPlayer.cl" with illegal data type conversion to boolean
        at sun.reflect.UnsafeFieldAccessorImpl.newGetIllegalArgumentException(Unknown Source) ~[?:1.8.0_431]
        at sun.reflect.UnsafeFieldAccessorImpl.newGetBooleanIllegalArgumentException(Unknown Source) ~[?:1.8.0_431]
        at sun.reflect.UnsafeObjectFieldAccessorImpl.getBoolean(Unknown Source) ~[?:1.8.0_431]
        at java.lang.reflect.Field.getBoolean(Unknown Source) ~[?:1.8.0_431]
        at com.loohp.interactivechat.nms.V1_12.canChatColor(V1_12.java:432) ~[?:?]
        at com.loohp.interactivechat.utils.PlayerUtils.canChatColor(PlayerUtils.java:162) ~[?:?]
        at com.loohp.interactivechat.listeners.ClientSettingPacket.handlePacketReceiving(ClientSettingPacket.java:74) ~[?:?]
        at com.loohp.interactivechat.listeners.ClientSettingPacket$2.onPacketReceiving(ClientSettingPacket.java:61) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:122) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:75) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:557) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketReceiving(PacketFilterManager.java:521) ~[?:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketReceiving(NetworkManagerInjector.java:118) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInboundPacket(NettyChannelInjector.java:500) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:33) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_431]
[20:41:52 ERROR]: Parameters:
  net.minecraft.server.v1_12_R1.PacketPlayInSettings@1d9be859[
    a=zh_cn
    b=6
    c=FULL
    d=true
    e=127
    f=Right
  ]
  
  [20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: java.lang.IllegalArgumentException: Attempt to get net.minecraft.server.v1_12_R1.EntityHuman$EnumChatVisibility field "net.minecraft.server.v1_12_R1.EntityPlayer.cl" with illegal data type conversion to boolean
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.newGetIllegalArgumentException(Unknown Source)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.newGetBooleanIllegalArgumentException(Unknown Source)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.getBoolean(Unknown Source)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at java.lang.reflect.Field.getBoolean(Unknown Source)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at com.loohp.interactivechat.nms.V1_12.canChatColor(V1_12.java:432)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at com.loohp.interactivechat.utils.PlayerUtils.canChatColor(PlayerUtils.java:162)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at com.loohp.interactivechat.listeners.OutMessagePacket.processPacket(OutMessagePacket.java:656)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at com.loohp.interactivechat.listeners.OutMessagePacket.access$300(OutMessagePacket.java:87)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at com.loohp.interactivechat.listeners.OutMessagePacket$1.lambda$onPacketSending$0(OutMessagePacket.java:499)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:41:31] [InteractiveChat Async ChatMessage Processing Thread #5/WARN]: 	at java.lang.Thread.run(Unknown Source)
