### ISSUE TITLE
java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by nicklly** [LOOHP/InteractiveChat#29]
Plugins Versions: 3.2.9

[15:37:19] [Craft Scheduler Thread - 102/WARN]: [InteractiveChat] Plugin InteractiveChat v3.2.9.13 generated an exception while executing task 5475
java.lang.NoSuchMethodError: me.clip.placeholderapi.PlaceholderAPIPlugin.getLocalExpansionManager()Lme/clip/placeholderapi/expansion/manager/LocalExpansionManager;
	at com.loohp.interactivechat.Utils.PlaceholderParser.getAllPlaceholdersContained(PlaceholderParser.java:51) ~[?:?]
	at com.loohp.interactivechat.Utils.PlaceholderParser.parse(PlaceholderParser.java:31) ~[?:?]
	at com.loohp.interactivechat.Modules.PlayernameDisplay.processPlayer(PlayernameDisplay.java:135) ~[?:?]
	at com.loohp.interactivechat.Modules.PlayernameDisplay.process(PlayernameDisplay.java:59) ~[?:?]
	at com.loohp.interactivechat.Listeners.ChatPackets.processPacket(ChatPackets.java:240) ~[?:?]
	at com.loohp.interactivechat.Listeners.ChatPackets.access$100(ChatPackets.java:52) ~[?:?]
	at com.loohp.interactivechat.Listeners.ChatPackets$1.lambda$onPacketSending$1(ChatPackets.java:100) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[kSpigot.jar:git-Paper-33d42c8e]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[kSpigot.jar:git-Paper-33d42c8e]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[kSpigot.jar:git-Paper-33d42c8e]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by LOOHP** [comment]
Which version of PlaceholderAPI are you using?

**Comment by nicklly** [comment]
> Which version of PlaceholderAPI are you using?

2.10.6

**Comment by LOOHP** [comment]
Please update to 2.10.9

**Comment by nicklly** [comment]
ok I try
