### ISSUE TITLE
errors when someone dies

### ISSUE THREAD

**Issue by BenRulez** [LOOHP/InteractiveChat#3]
Whenever someone dies a big error appears, using version 2.5.1 also using paper 1.16.1 #47

[08:06:32 INFO]: BenRulez fell from a high place
[08:06:32 INFO]: IC DEBUG BenRulez 4
[08:06:32 WARN]: java.lang.NullPointerException
[08:06:32 WARN]:        at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:58)
[08:06:32 WARN]:        at com.loohp.interactivechat.Listeners.ChatPackets$1.onPacketSending(ChatPackets.java:90)
[08:06:32 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[08:06:32 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[08:06:32 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[08:06:32 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[08:06:32 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:336)
[08:06:32 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[08:06:32 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378)
[08:06:32 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64)
[08:06:32 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343)
[08:06:32 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313)
[08:06:32 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[08:06:32 WARN]:        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.NetworkManager.b(NetworkManager.java:288)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.NetworkManager.dispatchPacket(NetworkManager.java:244)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.NetworkManager.sendPacket(NetworkManager.java:220)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1630)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.sendPacket(PlayerConnection.java:1603)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.PlayerList.sendAll(PlayerList.java:904)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.PlayerList.sendMessage(PlayerList.java:1254)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.EntityPlayer.die(EntityPlayer.java:712)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1261)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.EntityHuman.damageEntity(EntityHuman.java:761)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.EntityPlayer.damageEntity(EntityPlayer.java:833)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.EntityLiving.b(EntityLiving.java:1667)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.EntityHuman.b(EntityHuman.java:1543)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.Block.fallOn(Block.java:294)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.Entity.a(Entity.java:1082)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.EntityLiving.a(EntityLiving.java:246)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.EntityPlayer.a(EntityPlayer.java:1255)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1193)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInFlying.a(SourceFile:122)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004)
[08:06:32 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[08:06:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by LOOHP** [comment]
Thanks for reporting the bug, I am aware of this bug as well, it is due to some changes to Chat Components in 1.16 and spigot didn't exact change their API. So this is actually a spigot bug.

The problem will be fixed when buildtools start using the new chat API when building spigot

https://www.spigotmc.org/threads/componentserializer-throwing-error-on-1-16.447509/

**Comment by BenRulez** [comment]
Ok thanks

**Comment by LOOHP** [comment]
The issue should be fixed.
