### ISSUE TITLE
Running World Guard causes exceptions in Interactive Chat

### ISSUE THREAD

**Issue by HandyHat** [LOOHP/InteractiveChat#36]
I'm running `Paper version git-Paper-526 (MC: 1.16.5)` on Java 11.

When the only other plugins are Interactive Chat `3.2.10.3`, Placeholder API `2.10.9` ProtocolLib `4.6.0`, Vault `1.7.3` and World Edit `7.23`, there are no problems. Adding World Guard causes the following exception:

`[InteractiveChat] Unhandled exception occured in onPacketSending(PacketEvent) for InteractiveChat
java.lang.RuntimeException: Failed to clone net.minecraft.server.v1_16_R3.PacketPlayOutChat@6eb948cb (class net.minecraft.server.v1_16_R3.PacketPlayOutChat) with com.comphenix.protocol.events.PacketContainer$2$1@34a09f21
	at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:262) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:1142) ~[?:?]
	at com.loohp.interactivechat.Listeners.ChatPackets$1.onPacketSending(ChatPackets.java:108) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:293) ~[patched_1.16.5.jar:git-Paper-526]
	at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:249) ~[patched_1.16.5.jar:git-Paper-526]
	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:225) ~[patched_1.16.5.jar:git-Paper-526]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1742) ~[patched_1.16.5.jar:git-Paper-526]
	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1715) ~[patched_1.16.5.jar:git-Paper-526]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.sendMessage(CraftPlayer.java:2114) ~[patched_1.16.5.jar:git-Paper-526]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:274) ~[patched_1.16.5.jar:git-Paper-526]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:195) ~[patched_1.16.5.jar:git-Paper-526]
	at io.papermc.paper.adventure.ChatProcessor.complete(ChatProcessor.java:151) ~[patched_1.16.5.jar:git-Paper-526]
	at io.papermc.paper.adventure.ChatProcessor.lambda$process$1(ChatProcessor.java:73) ~[patched_1.16.5.jar:git-Paper-526]
	at io.papermc.paper.adventure.ChatProcessor.processLegacy(ChatProcessor.java:188) ~[patched_1.16.5.jar:git-Paper-526]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:60) ~[patched_1.16.5.jar:git-Paper-526]
	at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:1940) ~[patched_1.16.5.jar:git-Paper-526]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1855) ~[patched_1.16.5.jar:git-Paper-526]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1793) ~[patched_1.16.5.jar:git-Paper-526]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.5.jar:git-Paper-526]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]`
	
This occurs with both the stable version (`7.0.4`) and the latest development version (`7.0.5 Build 2105`) of World Guard. When this exception occurs, the person who sent the message cannot see their own message.

**Comment by LOOHP** [comment]
Try updating protocollib to the latest **dev build**

**Comment by HandyHat** [comment]
Yep that works great. Thanks!
