### ISSUE TITLE
Exception thrown when message is sent in chat

### ISSUE THREAD

**Issue by MoshiBar** [LOOHP/InteractiveChat#39]
if someone tries to send a message, the message won't show up and this exception will be thrown.
```
07.03 10:46:39 [Server] ERROR [InteractiveChat] Unhandled exception occured in onPacketSending(PacketEvent) for InteractiveChat
07.03 10:46:39 [Server] INFO java.lang.RuntimeException: Failed to clone net.minecraft.server.v1_16_R3.PacketPlayOutChat@3b3303b0 (class net.minecraft.server.v1_16_R3.PacketPlayOutChat) with com.comphenix.protocol.events.PacketContainer$2$1@3abc4249
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:262) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:1142) ~[?:?]
07.03 10:46:39 [Server] INFO at com.loohp.interactivechat.Listeners.ChatPackets$1.onPacketSending(ChatPackets.java:109) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
07.03 10:46:39 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:293) ~[patched_1.16.5.jar:git-Paper-"60e92c061"]
07.03 10:46:39 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:249) ~[patched_1.16.5.jar:git-Paper-"60e92c061"]
07.03 10:46:39 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:225) ~[patched_1.16.5.jar:git-Paper-"60e92c061"]
07.03 10:46:39 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1742) ~[patched_1.16.5.jar:git-Paper-"60e92c061"]
07.03 10:46:39 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1715) ~[patched_1.16.5.jar:git-Paper-"60e92c061"]
07.03 10:46:39 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.sendMessage(CraftPlayer.java:2144) ~[patched_1.16.5.jar:git-Paper-"60e92c061"]
07.03 10:46:39 [Server] INFO at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:274) ~[patched_1.16.5.jar:git-Paper-"60e92c061"]
07.03 10:46:39 [Server] INFO at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:195) ~[patched_1.16.5.jar:git-Paper-"60e92c061"]
07.03 10:46:39 [Server] INFO at io.papermc.paper.adventure.ChatProcessor.complete(ChatProcessor.java:151) ~[patched_1.16.5.jar:git-Paper-"60e92c061"]
07.03 10:46:39 [Server] INFO at io.papermc.paper.adventure.ChatProcessor.lambda$process$1(ChatProcessor.java:73) ~[patched_1.16.5.jar:git-Paper-"60e92c061"]
07.03 10:46:39 [Server] INFO at io.papermc.paper.adventure.ChatProcessor.processLegacy(ChatProcessor.java:188) ~[patched_1.16.5.jar:git-Paper-"60e92c061"]
07.03 10:46:39 [Server] INFO at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:60) ~[patched_1.16.5.jar:git-Paper-"60e92c061"]
07.03 10:46:39 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:1940) ~[patched_1.16.5.jar:git-Paper-"60e92c061"]
07.03 10:46:39 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1855) ~[patched_1.16.5.jar:git-Paper-"60e92c061"]
07.03 10:46:39 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1793) ~[patched_1.16.5.jar:git-Paper-"60e92c061"]
07.03 10:46:39 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.5.jar:git-Paper-"60e92c061"]
07.03 10:46:39 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
07.03 10:46:39 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
07.03 10:46:39 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
07.03 10:46:39 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
07.03 10:46:39 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
07.03 10:46:39 [Server] INFO Caused by: java.lang.IllegalArgumentException: Cannot clone TextComponentImpl{content="[", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[TextComponentImpl{content="Wrld", style=StyleImpl{color=NamedTextColor{value="#ffffff"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="]", style=StyleImpl{color=NamedTextColor{value="#ffffff"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="<", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="[O]", style=StyleImpl{color=NamedTextColor{value="#ffff55"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="MoshiBar", style=StyleImpl{color=NamedTextColor{value="#aa0000"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="> a<chat=ab1211a3-9afe-4d04-97df-a110ad857b46>", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}]} ( class net.kyori.adventure.text.TextComponentImpl): No cloner is suitable.
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:267) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.reflect.cloning.NullableCloner.clone(NullableCloner.java:43) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.reflect.cloning.FieldCloner.defaultTransform(FieldCloner.java:67) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.events.PacketContainer$2$1.access$200(PacketContainer.java:1153) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.events.PacketContainer$2$1$1.transformField(PacketContainer.java:1162) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.reflect.ObjectWriter.copyToInternal(ObjectWriter.java:115) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.reflect.ObjectWriter.copyTo(ObjectWriter.java:80) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.reflect.cloning.FieldCloner.clone(FieldCloner.java:91) ~[?:?]
07.03 10:46:39 [Server] INFO at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:260) ~[?:?]
07.03 10:46:39 [Server] INFO ... 35 more
07.03 10:46:39 [Server] ERROR Parameters: 
07.03 10:46:39 [Server] INFO net.minecraft.server.v1_16_R3.PacketPlayOutChat@3b3303b0[
07.03 10:46:39 [Server] INFO a=<null>
07.03 10:46:39 [Server] INFO components=<null>
07.03 10:46:39 [Server] INFO b=SYSTEM
07.03 10:46:39 [Server] INFO c=00000000-0000-0000-0000-000000000000
07.03 10:46:39 [Server] INFO ]
```

**Comment by LOOHP** [comment]
Please update to the latest **dev** build for protocollib

**Comment by andrewkm** [comment]
@MoshiBar use the latest build of Protocollib.
https://ci.dmulloy2.net/job/ProtocolLib/498/

**Comment by LOOHP** [comment]
Closing due to inactivity
