### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MEOW2006** [LOOHP/InteractiveChat#41]
it sends this a lot after some actions 
IDK what it is that

```
[20:12:51 ERROR]: [InteractiveChat] Unhandled exception occured in onPacketSending(PacketEvent) for InteractiveChat
java.lang.RuntimeException: Failed to clone net.minecraft.server.v1_16_R3.PacketPlayOutChat@bd4309 (class net.minecraft.server.v1_16_R3.PacketPlayOutChat) with com.comphenix.protocol.events.PacketContainer$2$1@2eb25a46
        at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:262) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:1142) ~[?:?]
        at com.loohp.interactivechat.Listeners.ChatPackets$1.onPacketSending(ChatPackets.java:109) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:293) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:249) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:225) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1742) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1715) ~[server.jar:git-Paper-545]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.sendMessage(CraftPlayer.java:2115) ~[server.jar:git-Paper-545]
        at net.kyori.adventure.audience.ForwardingAudience.sendMessage(ForwardingAudience.java:65) ~[server.jar:git-Paper-545]
        at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:207) ~[server.jar:git-Paper-545]
        at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:183) ~[server.jar:git-Paper-545]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.broadcastMessage(CraftServer.java:583) ~[server.jar:git-Paper-545]
        at org.bukkit.Bukkit.broadcastMessage(Bukkit.java:308) ~[server.jar:git-Paper-545]
        at eu.andycraftz.joinmessageplus.bukkit.MessagesL.onJoin(MessagesL.java:60) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor175.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[server.jar:git-Paper-545]
        at org.bukkit.plugin.EventExecutor$$Lambda$4708/0x000000007a801970.execute(Unknown Source) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[server.jar:git-Paper-545]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Paper-545]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:271) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:218) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.PlayerList$$Lambda$7763/0x00000000aaab4720.run(Unknown Source) ~[?:?]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:169) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:390) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:145) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1389) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:379) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1216) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3108/0x00000000edc7aee0.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Thread.java:836) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot clone TextComponentImpl{content="", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[TextComponentImpl{content="[", style=StyleImpl{color=NamedTextColor{value="#ffaa00"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="+", style=StyleImpl{color=NamedTextColor{value="#55ff55"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="]", style=StyleImpl{color=NamedTextColor{value="#ffaa00"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content=" ", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="[Owner] i_MaRTiin", style=StyleImpl{color=NamedTextColor{value="#ff5555"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}]} ( class net.kyori.adventure.text.TextComponentImpl): No cloner is suitable.
        at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:267) ~[?:?]
        at com.comphenix.protocol.reflect.cloning.NullableCloner.clone(NullableCloner.java:43) ~[?:?]
        at com.comphenix.protocol.reflect.cloning.FieldCloner.defaultTransform(FieldCloner.java:67) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer$2$1.access$200(PacketContainer.java:1153) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer$2$1$1.transformField(PacketContainer.java:1162) ~[?:?]
        at com.comphenix.protocol.reflect.ObjectWriter.copyToInternal(ObjectWriter.java:115) ~[?:?]
        at com.comphenix.protocol.reflect.ObjectWriter.copyTo(ObjectWriter.java:80) ~[?:?]
        at com.comphenix.protocol.reflect.cloning.FieldCloner.clone(FieldCloner.java:91) ~[?:?]
        at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:260) ~[?:?]
        ... 45 more
[20:12:51 ERROR]: Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayOutChat@bd4309[
    a=<null>
    components=<null>
    b=SYSTEM
    c=00000000-0000-0000-0000-000000000000
  ]
```

**Comment by LOOHP** [comment]
You need to be using the latest **dev** build of protocollib

**Comment by andrewkm** [comment]
@MEOW2006 use the latest build of Protocollib.
https://ci.dmulloy2.net/job/ProtocolLib/498/

**Comment by MEOW2006** [comment]
> You need to be using the latest **dev** build of protocollib

Okay, Thank you @LOOHP 


> @MEOW2006 use the latest build of Protocollib.
> https://ci.dmulloy2.net/job/ProtocolLib/498/

and thank you too @andrewkm
