### ISSUE TITLE
[BungeeCord] Exception in thread Timer

### ISSUE THREAD

**Issue by NeadApTar** [LOOHP/InteractiveChat#43]
```
20.03 00:23:52 [Server] ERROR Exception in thread "Timer-103" java.lang.NullPointerException
20.03 00:23:52 [Server] ERROR at com.loohp.interactivechat.Bungee.PluginMessageSendingBungee.requestMessageProcess(PluginMessageSendingBungee.java:254)
20.03 00:23:52 [Server] ERROR at com.loohp.interactivechat.Bungee.InteractiveChatBungee$7$1.run(InteractiveChatBungee.java:590)
20.03 00:23:52 [Server] ERROR at java.util.TimerThread.mainLoop(Timer.java:555)
20.03 00:23:52 [Server] ERROR at java.util.TimerThread.run(Timer.java:505)

20.03 00:23:52 [Server] ERROR Exception in thread "Timer-102" java.lang.NullPointerException
20.03 00:23:52 [Server] ERROR at com.loohp.interactivechat.Bungee.PluginMessageSendingBungee.requestMessageProcess(PluginMessageSendingBungee.java:254)
20.03 00:23:52 [Server] ERROR at com.loohp.interactivechat.Bungee.InteractiveChatBungee$7$1.run(InteractiveChatBungee.java:590)
20.03 00:23:52 [Server] ERROR at java.util.TimerThread.mainLoop(Timer.java:555)
20.03 00:23:52 [Server] ERROR at java.util.TimerThread.run(Timer.java:505)
```
Just updated from build 125 to 167 and this error appears every ~40 seconds. Using the latest Waterfall build (403).

**Comment by LOOHP** [comment]
Should be fixed in build 170 / 3.2.11.2.
