### ISSUE TITLE
Bungee error spam.

### ISSUE THREAD

**Issue by andrewkm** [LOOHP/InteractiveChat#44]
Using 3.2.11.4 Build 174
Bungee is continuously spamming the following:
```
[10:39:41] [Timer-724/ERROR]: Exception in thread "Timer-724" java.lang.NullPointerException
[10:39:41] [Timer-724/ERROR]: 	at com.loohp.interactivechat.Bungee.InteractiveChatBungee$5.run(InteractiveChatBungee.java:474)
[10:39:41] [Timer-724/ERROR]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[10:39:41] [Timer-724/ERROR]: 	at java.base/java.util.TimerThread.run(Timer.java:506)
[10:39:43] [Timer-725/ERROR]: Exception in thread "Timer-725" java.lang.NullPointerException
[10:39:43] [Timer-725/ERROR]: 	at com.loohp.interactivechat.Bungee.InteractiveChatBungee$5.run(InteractiveChatBungee.java:474)
[10:39:43] [Timer-725/ERROR]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[10:39:43] [Timer-725/ERROR]: 	at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by LOOHP** [comment]
Should be fixed in build 175.

**Comment by andrewkm** [comment]
Fixed.
