### ISSUE TITLE
error in 1.16.5

### ISSUE THREAD

**Issue by died375** [LOOHP/InteractiveChat#49]
[InteractiveChat] Unhandled exception occured in onPacketSending(PacketEvent) for InteractiveChat
java.lang.RuntimeException: Failed to clone net.minecraft.server.v1_16_R3.PacketPlayOutChat@1c32257c (class net.minecraft.server.v1_16_R3.PacketPlayOutChat) with com.comphenix.protocol.events.PacketContainer$2$1@1906b413
        at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:262) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:1142) ~[?:?]
        at com.loohp.interactivechat.Listeners.OutChatPacket$1.onPacketSending(OutChatPacket.java:115) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_16_R3.NetworkManager.writePacket(NetworkManager.java:488) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:337) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1860) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1833) ~[patched_1.16.5.jar:git-Purpur-1022]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.sendMessage(CraftPlayer.java:2126) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.kyori.adventure.audience.ForwardingAudience.sendMessage(ForwardingAudience.java:65) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:207) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:183) ~[patched_1.16.5.jar:git-Purpur-1022]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.broadcastMessage(CraftServer.java:583) ~[patched_1.16.5.jar:git-Purpur-1022]
        at com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask.run(EssentialsPlayerListener.java:335) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1022]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1378) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:391) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1291) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1017) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.5.jar:git-Purpur-1022]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot clone TextComponentImpl{content="", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[TextComponentImpl{content="ᴊᴏɪɴ ", style=StyleImpl{color=NamedTextColor{value="#55ff55"}, obfuscated=not_set, bold=true, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="MCAzkVn", style=StyleImpl{color=NamedTextColor{value="#ffffff"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}]} ( class net.kyori.adventure.text.TextComponentImpl): No cloner is suitable.
        at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:267) ~[?:?]
        at com.comphenix.protocol.reflect.cloning.NullableCloner.clone(NullableCloner.java:43) ~[?:?]
        at com.comphenix.protocol.reflect.cloning.FieldCloner.defaultTransform(FieldCloner.java:67) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer$2$1.access$200(PacketContainer.java:1153) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer$2$1$1.transformField(PacketContainer.java:1162) ~[?:?]
        at com.comphenix.protocol.reflect.ObjectWriter.copyToInternal(ObjectWriter.java:115) ~[?:?]
        at com.comphenix.protocol.reflect.ObjectWriter.copyTo(ObjectWriter.java:80) ~[?:?]
        at com.comphenix.protocol.reflect.cloning.FieldCloner.clone(FieldCloner.java:91) ~[?:?]
        at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:260) ~[?:?]
        ... 32 more
[08:29:31 ERROR]: Parameters:
  net.minecraft.server.v1_16_R3.PacketPlayOutChat@1c32257c[
    a=<null>
    components=<null>
    b=SYSTEM
    c=00000000-0000-0000-0000-000000000000
  ]

**Comment by died375** [comment]
fixed after update protocollib
