### ISSUE TITLE
Error upon trying to chat

### ISSUE THREAD

**Issue by satyrnhub** [LOOHP/InteractiveChat#54]
`[20:29:20 WARN]: java.lang.IllegalArgumentException: Cannot get ID of Modern Material
[20:29:20 WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[20:29:20 WARN]: 	at org.bukkit.Material.getId(Material.java:3612)
[20:29:20 WARN]: 	at com.loohp.interactivechat.hooks.viaversion.ItemRewriter.getConvertedItemStackNbtJson(ItemRewriter.java:108)
[20:29:20 WARN]: 	at com.loohp.interactivechat.utils.DataTypeIO.writeItemStack(DataTypeIO.java:183)
[20:29:20 WARN]: 	at com.loohp.interactivechat.bungeemessaging.BungeeMessageSender.forwardEquipment(BungeeMessageSender.java:86)
[20:29:20 WARN]: 	at com.loohp.interactivechat.modules.ItemDisplay.processWithoutCooldown(ItemDisplay.java:104)
[20:29:20 WARN]: 	at com.loohp.interactivechat.modules.ItemDisplay.process(ItemDisplay.java:90)
[20:29:20 WARN]: 	at com.loohp.interactivechat.listeners.OutChatPacket.processPacket(OutChatPacket.java:337)
[20:29:20 WARN]: 	at com.loohp.interactivechat.listeners.OutChatPacket.access$100(OutChatPacket.java:64)
[20:29:20 WARN]: 	at com.loohp.interactivechat.listeners.OutChatPacket$1.lambda$onPacketSending$1(OutChatPacket.java:129)
[20:29:20 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[20:29:20 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
[20:29:20 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:29:20 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[20:29:20 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[20:29:20 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[20:29:20 WARN]: java.lang.IllegalArgumentException: Cannot get ID of Modern Material
[20:29:20 WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[20:29:20 WARN]: 	at org.bukkit.Material.getId(Material.java:3612)
[20:29:20 WARN]: 	at com.loohp.interactivechat.hooks.viaversion.ItemRewriter.getConvertedItemStackNbtJson(ItemRewriter.java:108)
[20:29:20 WARN]: 	at com.loohp.interactivechat.utils.DataTypeIO.writeItemStack(DataTypeIO.java:183)
[20:29:20 WARN]: 	at com.loohp.interactivechat.bungeemessaging.BungeeMessageSender.forwardEquipment(BungeeMessageSender.java:86)
[20:29:20 WARN]: 	at com.loohp.interactivechat.modules.ItemDisplay.processWithoutCooldown(ItemDisplay.java:104)
[20:29:20 WARN]: 	at com.loohp.interactivechat.modules.ItemDisplay.process(ItemDisplay.java:90)
[20:29:20 WARN]: 	at com.loohp.interactivechat.listeners.OutChatPacket.processPacket(OutChatPacket.java:337)
[20:29:20 WARN]: 	at com.loohp.interactivechat.listeners.OutChatPacket.access$100(OutChatPacket.java:64)
[20:29:20 WARN]: 	at com.loohp.interactivechat.listeners.OutChatPacket$1.lambda$onPacketSending$1(OutChatPacket.java:129)
[20:29:20 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[20:29:20 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
[20:29:20 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:29:20 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[20:29:20 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[20:29:20 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)`

Not sure what could be causing this.

**Comment by LOOHP** [comment]
You might want to revert to 3.3.0.6 for now, there is a know problem in 3.3.1

**Comment by satyrnhub** [comment]
Closing as it works just fine in 3.3.0.6.
