### ISSUE TITLE
1.17 Bug

### ISSUE THREAD

**Issue by RobotHanzo** [LOOHP/InteractiveChat#62]
```
[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.getInt(Object)" because "this.ping" is null

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:71)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:49)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:95)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:345)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:296)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at com.loohp.interactivechat.utils.PlaceholderParser.parse0(PlaceholderParser.java:69)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at com.loohp.interactivechat.utils.PlaceholderParser.parse(PlaceholderParser.java:52)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at com.loohp.interactivechat.modules.PlayernameDisplay.processPlayer(PlayernameDisplay.java:85)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at com.loohp.interactivechat.modules.PlayernameDisplay.process(PlayernameDisplay.java:75)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at com.loohp.interactivechat.listeners.OutChatPacket.processPacket(OutChatPacket.java:337)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at com.loohp.interactivechat.listeners.OutChatPacket.access$200(OutChatPacket.java:71)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at com.loohp.interactivechat.listeners.OutChatPacket$1.lambda$onPacketSending$1(OutChatPacket.java:196)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

[19:21:04] [InteractiveChat Async ChatMessage Processing Thread #0/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
```
This spams the console every second.
Also the chat is filled with sender's UUID
![image](https://user-images.githubusercontent.com/36107150/122554950-350caa80-d06c-11eb-8634-a9f656dc8f3c.png)
I did install discordSRV and the addon, maybe its related?
(Using v4.0.0.12 and addon 4.0.0.11)

**Comment by LOOHP** [comment]
You need to update placeholder api and its player, and server expansion to the dev build which supports 1.17. You can find them on their discord server
https://discord.com/invite/0utOOIYX82aImw7h

**Comment by RobotHanzo** [comment]
That fixed the issue, thanks!
