### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by IamThomasisko** [LOOHP/InteractiveChat#68]
I have isuus chat doesnt work this is error`[ERROR] [InteractiveChat] Unhandled exception occured in onPacketSending(PacketEvent) for InteractiveChat
java.lang.RuntimeException: Failed to clone net.minecraft.server.v1_16_R3.PacketPlayOutChat@f3c25d8 (class net.minecraft.server.v1_16_R3.PacketPlayOutChat) with com.comphenix.protocol.events.PacketContainer$2$1@18a18201
at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:262) ~[?:?]
at com.comphenix.protocol.events.PacketContainer.deepClone(
at com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask.run(EssentialsPlayerListener.java:335) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[server.jar:git-Tuinity-"b12d0cc"]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[server.jar:git-Tuinity-"b12d0cc"]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1475) ~[server.jar:git-Tuinity-"b12d0cc"]
at net.minecraft.ser
10:31:58[ERROR] Parameters:
net.minecraft.server.v1_16_R3.PacketPlayOutChat@f3c25d8[
a=<null>
components=<null>
b=SYSTEM
c=00000000-0000-0000-0000-000000000000
]` But i see chat in discordSRV
![image](https://user-images.githubusercontent.com/87225455/126459870-d8972518-bc19-40ce-ba1c-e82639566b7d.png)
![image](https://user-images.githubusercontent.com/87225455/126459970-ba802a99-77d4-4fc1-a01b-0d779d990941.png)

**Comment by LOOHP** [comment]
Please update Protocollib

**Comment by IamThomasisko** [comment]
ok thanks it is working
