### ISSUE TITLE
onpacketsending errors

### ISSUE THREAD

**Issue by rohanrhu-smh** [LOOHP/InteractiveChat#74]
`[18:40:00] [Server thread/ERROR]: [InteractiveChat] Unhandled exception occured in onPacketSending(PacketEvent) for InteractiveChat
java.lang.RuntimeException: Failed to clone net.minecraft.server.v1_16_R3.PacketPlayOutChat@3e879e0b (class net.minecraft.server.v1_16_R3.PacketPlayOutChat) with com.comphenix.protocol.events.PacketContainer$2$1@44bf4154
	at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:262) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:1142) ~[?:?]
	at com.loohp.interactivechat.listeners.OutChatPacket$1.onPacketSending(OutChatPacket.java:121) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_16_R3.NetworkManager.writePacket(NetworkManager.java:507) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:356) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1985) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1958) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.sendMessage(CraftPlayer.java:2132) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:207) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:183) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:836) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:776) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at ch.njol.skript.Skript.dispatchCommand(Skript.java:1387) ~[?:?]
	at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:82) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:51) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
	at ch.njol.skript.events.EvtChat$1.execute(EvtChat.java:71) ~[?:?]
	at ch.njol.skript.events.EvtChat$1$1.call(EvtChat.java:90) ~[?:?]
	at ch.njol.skript.events.EvtChat$1$1.call(EvtChat.java:1) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftFuture.run(CraftFuture.java:88) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1489) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1402) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.IllegalArgumentException: Cannot clone TextComponentImpl{content="", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[TextComponentImpl{content="[!] ", style=StyleImpl{color=NamedTextColor{value="#ff5555"}, obfuscated=not_set, bold=true, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="Bilinmeyen Komut!", style=StyleImpl{color=NamedTextColor{value="#ff5555"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}]} ( class net.kyori.adventure.text.TextComponentImpl): No cloner is suitable.
	at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:267) ~[?:?]
	at com.comphenix.protocol.reflect.cloning.NullableCloner.clone(NullableCloner.java:43) ~[?:?]
	at com.comphenix.protocol.reflect.cloning.FieldCloner.defaultTransform(FieldCloner.java:67) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer$2$1.access$200(PacketContainer.java:1153) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer$2$1$1.transformField(PacketContainer.java:1162) ~[?:?]
	at com.comphenix.protocol.reflect.ObjectWriter.copyToInternal(ObjectWriter.java:115) ~[?:?]
	at com.comphenix.protocol.reflect.ObjectWriter.copyTo(ObjectWriter.java:80) ~[?:?]
	at com.comphenix.protocol.reflect.cloning.FieldCloner.clone(FieldCloner.java:91) ~[?:?]
	at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:260) ~[?:?]
	... 40 more
[18:40:00] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayOutChat@3e879e0b[
    a=<null>
    components=<null>
    b=SYSTEM
    c=00000000-0000-0000-0000-000000000000
  ]

[18:40:00] [Async Chat Thread - #0/ERROR]: [InteractiveChat] Unhandled exception occured in onPacketSending(PacketEvent) for InteractiveChat
java.lang.RuntimeException: Failed to clone net.minecraft.server.v1_16_R3.PacketPlayOutChat@23a90fa2 (class net.minecraft.server.v1_16_R3.PacketPlayOutChat) with com.comphenix.protocol.events.PacketContainer$2$1@44bf4154
	at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:262) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:1142) ~[?:?]
	at com.loohp.interactivechat.listeners.OutChatPacket$1.onPacketSending(OutChatPacket.java:121) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:29
![Adsız](https://user-images.githubusercontent.com/73096125/135882023-3f07d036-1cc5-4985-ac41-17515283953e.png)
6) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_16_R3.NetworkManager.writePacket(NetworkManager.java:507) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:356) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1985) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1958) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.sendMessage(CraftPlayer.java:2132) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:274) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at io.papermc.paper.adventure.ChatProcessor.complete(ChatProcessor.java:172) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at io.papermc.paper.adventure.ChatProcessor.processModern(ChatProcessor.java:135) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at io.papermc.paper.adventure.ChatProcessor.lambda$process$1(ChatProcessor.java:68) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:120) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:65) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:2184) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2099) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2037) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:43) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_301]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_301]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.IllegalArgumentException: Cannot clone TextComponentImpl{content="", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[TextComponentImpl{content="[", style=StyleImpl{color=NamedTextColor{value="#555555"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="] ", style=StyleImpl{color=NamedTextColor{value="#555555"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="| ", style=StyleImpl{color=NamedTextColor{value="#ff55ff"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="(", style=StyleImpl{color=NamedTextColor{value="#aaaaaa"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content=")  ", style=StyleImpl{color=NamedTextColor{value="#aaaaaa"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="KURUCU ", style=StyleImpl{color=NamedTextColor{value="#aa0000"}, obfuscated=not_set, bold=true, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="PATRON", style=StyleImpl{color=NamedTextColor{value="#ff5555"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content=" ? ", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="[inv] <chat=1761b119-6c11-32f2-a757-6d004003594c>", style=StyleImpl{color=NamedTextColor{value="#aaaaaa"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}]} ( class net.kyori.adventure.text.TextComponentImpl): No cloner is suitable.
	at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:267) ~[?:?]
	at com.comphenix.protocol.reflect.cloning.NullableCloner.clone(NullableCloner.java:43) ~[?:?]
	at com.comphenix.protocol.reflect.cloning.FieldCloner.defaultTransform(FieldCloner.java:67) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer$2$1.access$200(PacketContainer.java:1153) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer$2$1$1.transformField(PacketContainer.java:1162) ~[?:?]
	at com.comphenix.protocol.reflect.ObjectWriter.copyToInternal(ObjectWriter.java:115) ~[?:?]
	at com.comphenix.protocol.reflect.ObjectWriter.copyTo(ObjectWriter.java:80) ~[?:?]
	at com.comphenix.protocol.reflect.cloning.FieldCloner.clone(FieldCloner.java:91) ~[?:?]
	at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:260) ~[?:?]
	... 34 more
[18:40:00] [Async Chat Thread - #0/ERROR]: Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayOutChat@23a90fa2[
    a=<null>
    components=<null>
    b=CHAT
    c=00000000-0000-0000-0000-000000000000
  ]

[18:40:00] [Log4j2-TF-1-AsyncLogger[AsyncContext@7f31245a]-1/INFO]: [] | ()  KURUCU PATRON ? [PATRON's Inventory] `

This error is coming up on console whenever i try to send my inventory or item etc. on chat

**Comment by loohpjames** [comment]
You need to update your ProtocolLib.

**Comment by LOOHP** [comment]
You need to update ProtocolLib.
