### ISSUE TITLE
[BUG] java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by ErythroCraft** [LOOHP/InteractiveChat#82]
[08:52:01] [Server thread/ERROR]: Error occurred while enabling InteractiveChat v4.1.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: github/scarsz/discordsrv/dependencies/kyori/adventure/text/ComponentLike
        at com.loohp.interactivechat.InteractiveChat.onEnable(InteractiveChat.java:398) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:525) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:439) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:262) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at java.lang.Thread.run(Thread.java:833) [?:?]

Caused by: java.lang.ClassNotFoundException: github.scarsz.discordsrv.dependencies.kyori.adventure.text.ComponentLike
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 12 more

**Comment by ErythroCraft** [comment]
Spigot 1.18.1
InteractiveChat v4.1.0.0

**Comment by LOOHP** [comment]
The supported version of DiscordSRV is release 1.24.0
