### ISSUE TITLE
Error with MythicCrucible 1.0.1

### ISSUE THREAD

**Issue by IamAis** [LOOHP/InteractiveChat#86]
**Hi I'm a guy who used the MythicArtifact plugin on Minecraft, It has recently been updated to Crucible, On my server the plugin returns an error, despite I own all the APIs, there is someone who could help me. Thank you**
This is Error:

Error occurred while enabling MythicCrucible v1.0.1 (Is it up to date?)
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/destroystokyo/paper/event/player/PlayerJumpEvent
        at io.lumine.mythiccrucible.skills.SkillManager.<init>(SkillManager.java:103) ~[?:?]
        at io.lumine.mythiccrucible.MythicCrucible.enable(MythicCrucible.java:61) ~[?:?]
        at io.lumine.xikage.mythicmobs.utils.plugin.LuminePlugin.onEnable(LuminePlugin.java:72) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
Caused by: java.lang.NoClassDefFoundError: com/destroystokyo/paper/event/player/PlayerJumpEvent
        ... 13 more
Caused by: java.lang.ClassNotFoundException: com.destroystokyo.paper.event.player.PlayerJumpEvent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_311]
        ... 13 more

**Comment by LOOHP** [comment]
Hmm... Are you asking in the right place? This is the InteactiveChat repo.
