### ISSUE TITLE
Unable to resolve variables on other chat plugins

### ISSUE THREAD

**Issue by SheerYin** [LOOHP/InteractiveChat#93]
Current: git-Purpur-1604 (MC: 1.18.2)*
Previous: git-Paper-267 (MC: 1.18.2)

InteractiveChat-4.1.4.7.jar
ProtocolLib.jar Build #553 (2022-3-26 17:00:52)
PlaceholderAPI-2.11.1.jar

Even without other chat plugins, the parsed variables are not normal
![image](https://user-images.githubusercontent.com/83099762/161357584-4f3e1000-335f-496c-a144-f56f25f05b9e.png)

command '/interactivechat chat' error
`[08:50:01 INFO]: Yin issued server command: /interactivechat chat [item]
[08:50:01 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'interactivechat' in plugin InteractiveChat v4.1.4.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2389) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2200) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2181) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void com.comphenix.protocol.ProtocolManager.recieveClientPacket(org.bukkit.entity.Player, com.comphenix.protocol.events.PacketContainer)'
        at com.loohp.interactivechat.Commands.onCommand(Commands.java:360) ~[InteractiveChat-4.1.4.7.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 21 more`

**Comment by LOOHP** [comment]
Which version of ProtocolLib are you using?

**Comment by LOOHP** [comment]
Don't use ProtocolLib 5.0.0-SNAPSHOT yet, it is still unstable. Try dropping back down to 4.8.0

**Comment by SheerYin** [comment]
fixed, thanks
