### ISSUE TITLE
"InteractiveChat-4.1.4.13" Error While Opening Server

### ISSUE THREAD

**Issue by TeQTabanca** [LOOHP/InteractiveChat#95]
### Minecraft Version: 1.12.2 Spigot

Plugin Version: 4.1.4.13

### It gives an error when your plugin is Server enabling.

```
[20:39:07 ERROR]: Error occurred while enabling InteractiveChat v4.1.4.13 (Is it up to date?)
com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.exceptions.YamlReadingException: Could not parse YAML starting at line 330 . It should be a sequence (line should start with '-'), a mapping (line should contain ':') or it should be a plain scalar, but it has 561 lines, while a plain scalar should be only 1 line!
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.AllYamlLines.mappingSequenceOrPlainScalar(AllYamlLines.java:175) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.AllYamlLines.toYamlNode(AllYamlLines.java:124) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.Skip.toYamlNode(Skip.java:101) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.WellIndented.toYamlNode(WellIndented.java:174) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.SameIndentationLevel.toYamlNode(SameIndentationLevel.java:106) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.ReadYamlSequence.values(ReadYamlSequence.java:150) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.BaseYamlSequence.isEmpty(BaseYamlSequence.java:129) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.RtYamlPrinter.printNode(RtYamlPrinter.java:315) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.RtYamlPrinter.printNode(RtYamlPrinter.java:297) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.RtYamlPrinter.printMapping(RtYamlPrinter.java:164) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.RtYamlPrinter.printNode(RtYamlPrinter.java:338) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.RtYamlPrinter.printNode(RtYamlPrinter.java:297) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.RtYamlPrinter.printMapping(RtYamlPrinter.java:164) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.RtYamlPrinter.printNode(RtYamlPrinter.java:338) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.RtYamlPrinter.printNode(RtYamlPrinter.java:297) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.RtYamlPrinter.printMapping(RtYamlPrinter.java:164) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.RtYamlPrinter.print(RtYamlPrinter.java:77) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.YamlConfiguration.save(YamlConfiguration.java:123) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.YamlConfiguration.save(YamlConfiguration.java:116) ~[?:?]
        at com.loohp.interactivechat.libs.com.loohp.yamlconfiguration.YamlConfiguration.save(YamlConfiguration.java:101) ~[?:?]
        at com.loohp.interactivechat.config.Config.save(Config.java:145) ~[?:?]
        at com.loohp.interactivechat.datafixer.ConfigDataFixer.update(ConfigDataFixer.java:93) ~[?:?]
        at com.loohp.interactivechat.config.ConfigManager.lambda$setup$0(ConfigManager.java:63) ~[?:?]
        at com.loohp.interactivechat.config.Config.<init>(Config.java:113) ~[?:?]
        at com.loohp.interactivechat.config.Config.loadConfig(Config.java:64) ~[?:?]
        at com.loohp.interactivechat.config.ConfigManager.setup(ConfigManager.java:63) ~[?:?]
        at com.loohp.interactivechat.InteractiveChat.onEnable(InteractiveChat.java:393) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by LOOHP** [comment]
You have a problem with your config. Can you show that?

**Comment by LOOHP** [comment]
Can you send me the nbt of that item in text?
If you don't know how, hold the item in your main hand, and then run `/data get entity <your player> SelectedItem` in the server console.

**Comment by TeQTabanca** [comment]
Since my server is 1.12.2, custom models work with durability.

**Comment by LOOHP** [comment]
I've looked into this a bit. Can you give this build a try?
https://drive.google.com/file/d/1dKq8C0Zx8MCIUYnLomFDQAt3GJOqRWTB/view?usp=sharing

**Comment by TeQTabanca** [comment]
> I've looked into this a bit. Can you give this build a try? https://drive.google.com/file/d/1dKq8C0Zx8MCIUYnLomFDQAt3GJOqRWTB/view?usp=sharing

### Looks like now
.
![custom item](https://user-images.githubusercontent.com/89253304/165448571-b15542b3-6383-40d6-8364-124dcb2905e8.png)

**Comment by TeQTabanca** [comment]
**After I wrote the "/wm list" command of the weapon meachanics plugin, it kicked me out of the game and gave such an error on the console.**

```
[12:59:08 INFO]: [InteractiveChat] Cancelled a chat packet bounded to TeqTabanca that is 159525 characters long (Longer than maximum allowed in a chat packet), sending original unmodified message instead! [THIS IS NOT A BUG]
[12:59:08 ERROR]: io.netty.handler.codec.EncoderException: String too big (was 121449 bytes encoded, max 32767)
[12:59:08 INFO]: TeqTabanca lost connection: Disconnected
```

**Comment by LOOHP** [comment]
Does running that command throws this error without InteractiveChat?

**Comment by TeQTabanca** [comment]
yes

**Comment by LOOHP** [comment]
Then it shouldn't be an InteractiveChat issue
