### ISSUE TITLE
Failing to load on startup: NoSuchFieldError: CHAT_PREVIEW

### ISSUE THREAD

**Issue by Bunnky** [LOOHP/InteractiveChat#99]
When loading a 1.19 paper server (1.19-31) with most recent version of IC (v4.2.2.0), IC fails on enabling. Error: https://pastebin.com/jgcMexWV

```
[13:46:31] [Server thread/ERROR]: Error occurred while enabling InteractiveChat v4.2.2.0 (Is it up to date?)
java.lang.NoSuchFieldError: CHAT_PREVIEW
	at com.loohp.interactivechat.listeners.OutMessagePacket.<clinit>(OutMessagePacket.java:151) ~[InteractiveChat-4.2.2.0.jar:?]
	at com.loohp.interactivechat.InteractiveChat.onEnable(InteractiveChat.java:463) ~[InteractiveChat-4.2.2.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.jar:git-Paper-31]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.19.jar:git-Paper-31]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-31]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-31]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-31]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-31]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-31]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
```
[13:46:31] [Server thread/ERROR]: Error occurred while disabling InteractiveChat v4.2.2.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.loohp.interactivechat.objectholders.NicknameManager.close()" because "com.loohp.interactivechat.InteractiveChat.nicknameManager" is null
	at com.loohp.interactivechat.InteractiveChat.onDisable(InteractiveChat.java:601) ~[InteractiveChat-4.2.2.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:573) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.jar:git-Paper-31]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.19.jar:git-Paper-31]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-31]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-31]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-31]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-31]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-31]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Server Software:** Paper 1.19-31
**Plugin Version:** 4.2.2.0

Using CMI 9.2.0.0 for chat formatting.

**Comment by LOOHP** [comment]
Which version of ProtocolLib are you using?

**Comment by Bunnky** [comment]
4.8, [most recent ](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.8.0). I read about 5.0 SNAPSHOT for 1.19 fix, but if that's public I cannot find it

**Comment by vachanmn123** [comment]
I have a simmilar issue, I have attached logs below

```java
08:00:46 INFO]: [InteractiveChat] Enabling InteractiveChat v4.2.2.0
[08:00:53 INFO]: [InteractiveChat] Opened Sqlite database successfully
[08:00:53 ERROR]: Error occurred while enabling InteractiveChat v4.2.2.0 (Is it up to date?)
java.lang.NoSuchFieldError: CHAT_PREVIEW
        at com.loohp.interactivechat.listeners.OutMessagePacket.<clinit>(OutMessagePacket.java:151) ~[InteractiveChat-4.2.2.0.jar:?]
        at com.loohp.interactivechat.InteractiveChat.onEnable(InteractiveChat.java:463) ~[InteractiveChat-4.2.2.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[purpur-1.19.jar:git-Purpur-1670]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1670]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:00:53 INFO]: [InteractiveChat] Disabling InteractiveChat v4.2.2.0
[08:00:53 ERROR]: Error occurred while disabling InteractiveChat v4.2.2.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.loohp.interactivechat.objectholders.NicknameManager.close()" because "com.loohp.interactivechat.InteractiveChat.nicknameManager" is null
        at com.loohp.interactivechat.InteractiveChat.onDisable(InteractiveChat.java:601) ~[InteractiveChat-4.2.2.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:573) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[purpur-1.19.jar:git-Purpur-1670]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1670]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Server Version: `git-Purpur-1670 (MC: 1.19)`
Plugin Version: `InteractiveChat-4.2.2.0`

Plugins list:
```log
EasyWhitelist*,
InteractiveChat-4.2.2.0, 
PlaceholderAPI-2.11.1, 
ProtocolLib v4.8.0, 
SkinsRestorer 14.2.1, 
Vault 1.7.3
```

**Comment by LOOHP** [comment]
You must use ProtocolLib 5.0.0-SNAPSHOT for 1.19
